/* ══════════════════════════════════════════════════════════════
   BANCO DE PREGUNTAS — CEA El Fénix (201 preguntas)
   Fuente: BANCO_DE_PREGUNTAS_CEA_EL_FENIX_ACTUALIZADO.docx
   Preguntas con señal visual incluyen el campo 'img'
══════════════════════════════════════════════════════════════ */
const PREGUNTAS = [
  // ── MOVILIDAD
  {cat:"Movilidad", q:"¿DE LAS SIGUIENTES AFIRMACIONES SOBRE MOVILIDAD CUAL ES CORRECTA?", opts:["MOVILIDAD SALUDABLE COMO UN PROPÓSITO DEL SECTOR SALUD. MOVERSE MÁS VECES, MÁS TIEMPO, SIN DEPENDENCIA DE MEDIOS MOTORIZADOS Y CON ACCESIBILIDAD PARA TODOS","MOVILIDAD SEGURA, ES UN MEDIO PARA MANTENER Y PROMOVERLA SALUD. EN DONDE LAS PERSONAS SE MUEVEN COTIDIANAMENTE SIN GENERAR RIESGOS NI EXPOSICIÓN A AMENAZAS CONTRA LA VIDA Y LA SALUD","MOVILIDAD SOSTENIBLE, ES UN MODO QUE BUSCA ARTICULAR ACTORES Y SECTORES DE MANERA RACIONAL, EQUITATIVA Y FUNCIONAL EN LA PRESERVACIÓN DE LA CALIDAD DEL AIRE Y DEL AMBIENTE NATURAL Y ANTRÓPICO CON ACCIONES A NIVEL AMBIENTAL, ECONÓMICO, POLÍTICO Y SOCIAL","TODAS LAS ANTERIORES SON CORRECTAS"], ans:3, exp:"La respuesta correcta es: TODAS LAS ANTERIORES SON CORRECTAS."},
  // ── SEÑALES
  {cat:"Señales", q:"¿QUE ES VELOCIDAD INADECUADA?", opts:["NO DETENERSE ANTE ALGUN OBSTÁCULO QUE SURJA EN LA CONDUCCIÓN","NO RESPETAR LAS SEÑALES QUE LIMITAN LA VELOCIDAD","VELOCIDAD NO ADAPTADA A LAS CONDICIONES DE LA VÍA, DEL TRÁFICO, DEL VEHÍCULO O DEL PROPIO CONDUCTOR","TODAS LAS ANTERIORES CON CORRECTAS"], ans:3, exp:"La respuesta correcta es: TODAS LAS ANTERIORES CON CORRECTAS."},
  // ── CONDUCCIÓN SEGURA
  {cat:"Conducción Segura", q:"¿LA VELOCIDAD INFLUYE EN EL CAMPO VISUAL DEL CONDUCTOR?", opts:["NO, ES IGUAL LA VISIÓN A CUALQUIER VELOCIDAD","SI, A MENOR VELOCIDAD MENOS VISIÓN","NO, A MAYOR VELOCIDAD MÁS VISIÓN","SI, EL CAMPO VISUAL DISMINUYE AL AUMENTAR LA VELOCIDAD"], ans:3, exp:"La respuesta correcta es: SI, EL CAMPO VISUAL DISMINUYE AL AUMENTAR LA VELOCIDAD."},
  // ── PRIMEROS AUXILIOS
  {cat:"Primeros Auxilios", q:"¿IDENTIFIQUE CUALES SON LOS ACTORES MÁS VULNERABLES DADO AL NIVEL DE GRAVEDAD DE SUS LESIONES EN CASO DE UN SINIESTRO VIAL?", opts:["EL PEATÓN, USUARIO BICICLETA Y USUARIO MOTOCICLETA","LOS PASAJEROS DE UN BUS","SOLO LOS PEATONES","LOS USUARIOS DE BICICLETA"], ans:0, exp:"La respuesta correcta es: EL PEATÓN, USUARIO BICICLETA Y USUARIO MOTOCICLETA."},
  // ── MOTOCICLISTAS
  {cat:"Motociclistas", q:"CUÁLES DE LOS SIGUIENTES MEDIOS DE TRANSPORTE HACEN PARTE DEL TRANSPORTE ACTIVO Y SOSTENIBLE?", opts:["A PIE Y EN BICICLETA","A PIE, BICICLETAS, PATINES. MONOPATINES Y PATINETAS","A Y B SON CORRECTAS","EN VEHÍCULO PARTICULAR Y MOTOCICLETAS"], ans:2, exp:"La respuesta correcta es: A Y B SON CORRECTAS."},
  // ── GENERAL
  {cat:"General", q:"SE PUEDE REALIZAR EL CAMBIO DE UBICACIÓN DE LA PLACA EN UN VEHICULO AL RECOMENDADO", opts:["NO, LA PLACA DEBE IR EN EL LUGAR ESTABLECIDO QUE VIENE DE FABRICA","SI, LO IMPORTANTE ES QUE LA PLACA TENGA VISIBILIDAD DESDE LA PARTE DE ATRÁS","SÍ, PERO SE DEBE SACAR UN PERMISO PARA PODER REALIZAR ESTE CAMBIO DE UBICACIÓN","NINGUNA DE LAS ANTERIORES"], ans:1, exp:"La respuesta correcta es: SI, LO IMPORTANTE ES QUE LA PLACA TENGA VISIBILIDAD DESDE LA PARTE DE ATRÁS."},
  // ── CONDUCCIÓN SEGURA
  {cat:"Conducción Segura", q:"¿QUE SE ENTIENDE POR CONDUCIR A LA DEFENSIVA?", opts:["HACER VALER SUS DERECHOS EN TODO MOMENTO","FRENAR ANTES DE CADA CRUCE","TOMAR EN CUENTA LOS POSIBLES ERRORES DE LOS DEMÁS","CULPAR A LOS DEMÁS POR SUS ERRORES AL CONDUCIR"], ans:2, exp:"La respuesta correcta es: TOMAR EN CUENTA LOS POSIBLES ERRORES DE LOS DEMÁS."},
  // ── GENERAL
  {cat:"General", q:"LA CONDUCCIÓN PREVENTIVA SE BASA EN 3 PRINCIPIOS BÁSICOS QUE SON:", opts:["VISIÓN Y GESTIÓN DEL ESPACIO","VISIÓN, ANTICIPACIÓN Y GESTIÓN DEL TIEMPO","VISIÓN, ANTICIPACIÓN Y GESTIÓN DEL ESPACIO","NINGUNA DE LAS ANTERIORES"], ans:2, exp:"La respuesta correcta es: VISIÓN, ANTICIPACIÓN Y GESTIÓN DEL ESPACIO."},
  // ── MECÁNICA
  {cat:"Mecánica", q:"PARA CONDUCIR DE MANERA EFICIENTE SE DEBE:", opts:["ACELERAR EL VEHÍCULO A LAS REVOLUCIONES NECESARIAS PARA PREVENIR POSIBLES DAÑOS DEL MOTOR EL AHORRO DE COMBUSTIBLE Y LA NO CONTAMINACION AMBIENTAL","ACELERAR EL VEHÍCULO A LAS MÁXIMAS REVOLUCIONES PARA PODER TENER UN ARRANQUE QUE SEA RÁPIDO Y EFICAZ","TRATAR DE ARRANCAR EL VEHÍCULO SOLAMENTE CON EL PUNTO DE CONTACTO SIN HACER EL USO DE LAS REVOLUCIONES","NINGUNA DE LAS ANTERIORES"], ans:0, exp:"La respuesta correcta es: ACELERAR EL VEHÍCULO A LAS REVOLUCIONES NECESARIAS PARA PREVENIR POSIBLES DAÑOS DEL MOTOR EL AHORRO DE COMBUSTIBLE Y LA NO CONTAMINACION AMBIENTAL."},
  // ── INFRACCIONES
  {cat:"Infracciones", q:"QUE SANCIÓN DE MULTA SERÁ IMPUESTA AL CONDUCTOR DE UN VEHICULO POR ESTACIONAR EL VEHÍCULO EN SITIOS PROHIBIDOS?", opts:["4 SMDLV","15 SMDLV","8 SMDLV","30 SMDLV"], ans:1, exp:"La respuesta correcta es: 15 SMDLV."},
  // ── DOCUMENTOS
  {cat:"Documentos", q:"CUANTO ES EL VALOR DE LA INFRACCION DE CONDUCIR UN VEHICULO SIN LLEVAR CONSIGO LA LICENCIA DE CONDUCCIÓN", opts:["15 SMLDV","8 SMLDV","2 SMLDV","12 SMLDV"], ans:1, exp:"La respuesta correcta es: 8 SMLDV."},
  // ── MECÁNICA
  {cat:"Mecánica", q:"QUE SIGNIFICA EL SISTEMA ABS EN UN VEHICULO", opts:["SISTEMA DE RETENCIÓN INFANTIL","SISTEMA DE FRENOS ANTIBLOQUEO","SISTEMA DE ACELERACIÓN","NINGUNA DE LAS ANTERIORES"], ans:1, exp:"La respuesta correcta es: SISTEMA DE FRENOS ANTIBLOQUEO."},
  // ── SEÑALES
  {cat:"Señales", q:"¿DE LOS SIGUIENTES COMPORTAMIENTOS CUAL VULNERA MÁS LA CONDICIÓN DE ACTORES VIALES?", opts:["IGNORAR LAS SEÑALES DE TRÁNSITO","PASAR LOS SEMÁFOROS EN ROJO","GIRAR SIN MIRAR ATRÁS NI HACER SEÑALES MANUALES. USAR LOS CASCOS SIN ABROCHAR Y ZIGZAGUEAR ENTRE VEHÍCULOS","TODAS LAS ANTERIORES"], ans:3, exp:"La respuesta correcta es: TODAS LAS ANTERIORES."},
  // ── MOTOCICLISTAS
  {cat:"Motociclistas", q:"14 CUÁL ES EL ACTOR MÁS VULNERABLE EN LA VÍA POR LO TANTO REQUIERE DE ESPECIAL PROTECCIÓN?", opts:["MOTOCICLISTA","PEATONES","CONDUCTOR DE MOTOCICLETA","CONDUCTOR DE VEHÍCULOS"], ans:1, exp:"La respuesta correcta es: PEATONES."},
  // ── CONDUCCIÓN SEGURA
  {cat:"Conducción Segura", q:"¿CUÁL ES LA VELOCIDAD MÁXIMA PERMITIDA EN ZONAS ESCOLARES Y RESIDENCIALES EN LAS VÍAS RURALES?", opts:["30KM/H","60KM/H","20KM/H","90KRN/H"], ans:0, exp:"La respuesta correcta es: 30KM/H."},
  // ── DOCUMENTOS
  {cat:"Documentos", q:"¿CUANDO HABLAMOS DE AUTORREGULACIÓN NOS REFERIMOS A?", opts:["PASAR EL SEMÁFORO EN LUZ AMARILLA","CONDUCIR UN VEHÍCULO SIN TENER LA LICENCIA DE CONDUCCIÓN","COMPRENDER LA IMPORTANCIA DE ACATAR LAS NORMAS DE TRÁNSITO DE FORMA AUTÓNOMA PARA NO PONER EN RIESGO SU VIDA Y LA DE LOS DEMAS","TODAS LAS ANTERIORES"], ans:2, exp:"La respuesta correcta es: COMPRENDER LA IMPORTANCIA DE ACATAR LAS NORMAS DE TRÁNSITO DE FORMA AUTÓNOMA PARA NO PONER EN RIESGO SU VIDA Y LA DE LOS DEMAS."},
  // ── AUTORIDADES Y NORMAS
  {cat:"Autoridades y Normas", q:"A HABLAR DE AUTORIDADES DE TRANSITO NOS REFERIMOS A:", opts:["POLICIA","SECRETARIA DE EDUCACIÓN","AGENTES DE TRÁNSITO Y POLICÍA DE TRANSITO","TODAS ANTERIORES"], ans:2, exp:"La respuesta correcta es: AGENTES DE TRÁNSITO Y POLICÍA DE TRANSITO."},
  // ── DOCUMENTOS
  {cat:"Documentos", q:"QUE DOCUMENTOS SE DEBE PRESENTAR A UNA AUTORIDAD DE TRANSITO?", opts:["LICENCIA DE CONDUCCIÓN Y CEDULA DE CIUDADANÍA","SOAT Y REVISIÓN TECNOMECÁNICA","LICENCIA DE TRANSITO","TODAS LAS ANTERIORES"], ans:3, exp:"La respuesta correcta es: TODAS LAS ANTERIORES."},
  // ── MOTOCICLISTAS
  {cat:"Motociclistas", q:"CUANTO ES EL VALOR DEL COMPARENDO POR NO PORTAR EL CASCO REGLAMENTARIO EN LA MOTOCICLETA.", opts:["8 SMDLV","15 SMDLV","30 SMDLV","45 SMDLV"], ans:1, exp:"La respuesta correcta es: 15 SMDLV."},
  // ── AUTORIDADES Y NORMAS
  {cat:"Autoridades y Normas", q:"EN LOS ASPECTOS LEGALES QUE LEY RIGE A LOS CONDUCTORES EN COLOMBIA", opts:["LEY 769 DEL 2002","LEY 1801 DEL 2016","CONSTITUCIÓN POLÍTICA 1991","LEY 1122 DEL 2007"], ans:0, exp:"La respuesta correcta es: LEY 769 DEL 2002."},
  // ── MOVILIDAD
  {cat:"Movilidad", q:"21 QUIEN SE ENCARGA DE EXPEDIR LOS DECRETOS Y RESTRICCIONES ESPECIFICAS EN LA MOVILIDAD DE TU CIUDAD?", opts:["EL MINISTERIO DEL INTERIOR","LA SECRETARIA DE EDUCACIÓN","SECRETARIA DE TRANSITO","EL ALCALDE"], ans:3, exp:"La respuesta correcta es: EL ALCALDE."},
  // ── PEATONES Y CICLISTAS
  {cat:"Peatones y Ciclistas", q:"DE LOS SIGUIENTES ENUNCIADOS CUAL ES CONSIDERADA COMO UNA CONDUCTA INAPROPIADA EN LA VIA.", opts:["DETENER EL VEHICULO ANTES DE LA LÍNEA DE PASO PEATONAL","CEDER EL PASO","RESPETAR LOS LÍMITES DE VELOCIDAD","SUBIR O ESTACIONAR LAS MOTOS EN LOS ANDENES DE LAS CASAS"], ans:3, exp:"La respuesta correcta es: SUBIR O ESTACIONAR LAS MOTOS EN LOS ANDENES DE LAS CASAS."},
  // ── GENERAL
  {cat:"General", q:"CUÁL ES LA EMOCIÓN QUE DEBO CONTROLAR EN UNA CONGESTIÓN VEHICULAR SI VOY TARDE PARA UNA CITA.", opts:["LA IRA","EL RESPETO","LA TOLERANCIA","TODAS LAS ANTERIORES"], ans:3, exp:"La respuesta correcta es: TODAS LAS ANTERIORES."},
  // ── PRIMEROS AUXILIOS
  {cat:"Primeros Auxilios", q:"POR QUÉ NO DEBO CONDUCIR BAJO EL EFECTO DEL ALCOHOL", opts:["POR QUÉ VOY MÁS LENTO","POR QUÉ VOY FELIZ","POR QUÉ PUEDO CAUSAR UN ACCIDENTE","PORQUE AUMENTA MI CAPACIDAD DE REACCIÓN"], ans:2, exp:"La respuesta correcta es: POR QUÉ PUEDO CAUSAR UN ACCIDENTE."},
  // ── CONDUCCIÓN SEGURA
  {cat:"Conducción Segura", q:"CUAL ES LA VELOCIDAD MÁXIMA PERMITIDA EN COLOMBIA EN EL PERIMETRO RURAL", opts:["60 KM/H","80 KM/H","120 KM/H","100 KM/H"], ans:1, exp:"La respuesta correcta es: 80 KM/H."},
  // ── SEÑALES
  {cat:"Señales", q:"QUE SIGNIFICA LA SIGUIENTE SEÑAL", opts:["ZONA DE DISCAPACITADOS","PARE","ZONA DE SILLA DE RUEDAS","NINGUNA DE LAS ANTERIORES"], ans:0, exp:"La respuesta correcta es: ZONA DE DISCAPACITADOS.", img:"./imgs/preguntas/q26_discapacitados.png"},
  {cat:"Señales", q:"USTED LLEGA A UNA INTERSECCIÓN REGULADA POR UN SEMÁFORO QUE SE ENCUENTRA EN ROJO, AL MISMO TIEMPO, UN POLICÍA O AGENTE DE TRÁNSITO LE INDICA QUE AVANCE. ¿QUÉ DEBE HACER USTED?", opts:["DETENERSE PORQUE LA LUZ ROJA LO INDICA","AVANZAR, PORQUE LAS INSTRUCCIONES DE UN AGENTE, PREVALECEN SOBRE LAS SEÑALES DE TRÁNSITO","AVANZAR, SOLO SI DETRÁS SUYO NO VIENE OTROS VEHÍCULOS","AVANZAR, SOLO SI ESTÁ SEGURO QUE LA LUZ ROJA VA A CAMBIAR"], ans:1, exp:"La respuesta correcta es: AVANZAR, PORQUE LAS INSTRUCCIONES DE UN AGENTE, PREVALECEN SOBRE LAS SEÑALES DE TRÁNSITO."},
  // ── GENERAL
  {cat:"General", q:"QUE ES UNA VÍA", opts:["ESPACIO DESTINADO AL PASO DE VEHÍCULOS O PERSONAS QUE VAN DE UN LUGAR A OTRO","LUGAR POR DONDE SE CIRCULA O DESPLAZA","INFRAESTRUCTURA QUE PERMITE LA CIRCULACIÓN EN CONDICIONES DE SEGURIDAD A LOS ACTORES VIALES","TODAS LAS ANTERIORES"], ans:3, exp:"La respuesta correcta es: TODAS LAS ANTERIORES."},
  // ── ALCOHOL Y SUSTANCIAS
  {cat:"Alcohol y Sustancias", q:"LA PERSONA QUE SE ENCUENTRE CONDUCIENDO BAJO LOS EFECTOS DEL ALCOHOL EN TERCER GRADO SERÁ SANCIONADO DE LA SIGUIENTE MANERA", opts:["720 SMLDV Y SUSPENSIÓN DÉ LA LICENCIA DE CONDUCCIÓN DURANTE DIEZ (10) AÑOS","180 SMLDV Y SUSPENSIÓN DE LA LICENCIA DE CONDUCCIÓN QUINCE AÑOS(15) AÑOS","90 SMLDV Y SUSPENSIÓN DE LA LICENCIA DE CONDUCCIÓN DURANTE DOS (2) AÑOS","360 SMLDV Y SUSPENSIÓN DE LA LICENCIA DE CONDUCCIÓN DURANTE SEIS (6) AÑOS"], ans:0, exp:"La respuesta correcta es: 720 SMLDV Y SUSPENSIÓN DÉ LA LICENCIA DE CONDUCCIÓN DURANTE DIEZ (10) AÑOS."},
  // ── PRIMEROS AUXILIOS
  {cat:"Primeros Auxilios", q:"¿CUÁL DE LAS SIGUIENTES AFIRMACIONES SON VERDADERAS?", opts:["EL CONDUCTOR IMPRUDENTE, CONDUCE A ALTAS VELOCIDADES","EL CONDUCTOR IMPRUDENTE, CREA SITUACIONES DE RIESGO CON ALTA FRECUENCIA","CON FRECUENCIA LOS JÓVENES, CONDUCEN A ALTAS VELOCIDADES Y SE VEN MAS INVOLUCRADOS EN ACCIDENTES DE TRANSITO","TODAS LAS ANTERIORES"], ans:3, exp:"La respuesta correcta es: TODAS LAS ANTERIORES."},
  // ── GENERAL
  {cat:"General", q:"ENTRE EL ACELERADOR Y EL EMBRAGUE CUAL ES EL ENCARGADO DE DARLE EL MOVIMIENTO AL VEHÍCULO", opts:["EL ACELERADOR","EL EMBRAGUE","AMBOS DAN EL MOVIMIENTO","NINGUNO DE ESTOS"], ans:2, exp:"La respuesta correcta es: AMBOS DAN EL MOVIMIENTO."},
  // ── INFRACCIONES
  {cat:"Infracciones", q:"QUE SANCIÓN SERÁ IMPUESTA AL CONDUCTOR POR PARQUEAR EN SITIOS PROHIBIDOS.", opts:["8 SMDLV","15 SMDLV","30 SMDLV","45 SMDLV"], ans:1, exp:"La respuesta correcta es: 15 SMDLV."},
  // ── SEÑALES
  {cat:"Señales", q:"CUALES SON LAS SEÑALES QUE TIENE MAYOR PRELACIÓN?", opts:["SEÑALES Y ORDENES EMITIDAS POR UN AGENTE DE TRANSITO","SEÑALES TRANSITORIAS Y SEMÁFOROS","SEÑALES VERTICALES Y SEÑALES HORIZONTALES","TODAS LAS ANTERIORES"], ans:0, exp:"La respuesta correcta es: SEÑALES Y ORDENES EMITIDAS POR UN AGENTE DE TRANSITO."},
  // ── GENERAL
  {cat:"General", q:"UN CARRIL EXCLUSIVO ES:", opts:["DONDE VAN MOTOS Y CARROS","UN CICLO RUTA","UNA AVENIDA","TRÁNSITO DE UNA SOLA CLASE DE VEHÍCULOS"], ans:3, exp:"La respuesta correcta es: TRÁNSITO DE UNA SOLA CLASE DE VEHÍCULOS."},
  // ── PEATONES Y CICLISTAS
  {cat:"Peatones y Ciclistas", q:"QUE ES UNA CICLO RUTA?", opts:["COMPLETAMENTE DE BICICLETA Y PEATONES","VIA EXCLUSIVA PARA EL TRÁNSITO DE BICICLETA","SESIÓN DE LA CALZADA DESTINA OCASIONALMENTE A ESPARCIMIENTO DE DEPORTE","NINGUNA DE LAS ANTERIORES"], ans:1, exp:"La respuesta correcta es: VIA EXCLUSIVA PARA EL TRÁNSITO DE BICICLETA."},
  // ── SEÑALES
  {cat:"Señales", q:"SI QUIERO GIRAR A LA DERECHA EN UN SEMÁFORO CON FLECHA VERDE ILUMINADA. ¿SE TIENE PREFERENCIA DE PASO?", opts:["NO TENGO PREFERENCIA PORQUE LA LUZ ROJA PROHÍBE GIRAR","NO TENGO PREFERENCIA, PERO LA LUZ VERDE ME PERMITE GIRAR SIEMPRE Y CUANDO TOME LAS DEBIDAS PRECAUCIONES","SI TENGO PREFERENCIA PORQUE LA FLECHA ME LO PERMITE","NINGUNA DE LAS ANTERIORES"], ans:2, exp:"La respuesta correcta es: SI TENGO PREFERENCIA PORQUE LA FLECHA ME LO PERMITE."},
  // ── GENERAL
  {cat:"General", q:"LOS SISTEMAS DE SEGURIDAD PASIVA, ¿INCLUYEN LOS CINTURONES DE SEGURIDAD, AIRBAG, APOYACABEZAS Y CASCOS?", opts:["NO","SI","SÍ, PERO SIN LOS CASCOS","NINGUNA DE LAS ANTERIORES"], ans:1, exp:"La respuesta correcta es: SI."},
  // ── PRIMEROS AUXILIOS
  {cat:"Primeros Auxilios", q:"¿CUÁL ES LA FUNCIÓN DE LOS SISTEMAS DE SEGURIDAD PASIVA?", opts:["AMINORAR LOS DAÑOS CAUSADOS POR UN ACCIDENTE A LAS PERSONAS","EVITAR QUE SE PRODUZCA UN ACCIDENTE","AMINORAR LOS DAÑOS CAUSADOS POR UN ACCIDENTE A LOS VEHÍCULOS","TODAS LAS ANTERIORES"], ans:0, exp:"La respuesta correcta es: AMINORAR LOS DAÑOS CAUSADOS POR UN ACCIDENTE A LAS PERSONAS."},
  // ── MECÁNICA
  {cat:"Mecánica", q:"EL DISPOSITIVO QUE TRANSMITE LA ENERGÍA DEL MOTOR A LAS RUEDAS MOTRICES SE LLAMA:", opts:["TRANSMISIÓN","DIRECCIÓN","FRENO","EMBRAGUE"], ans:0, exp:"La respuesta correcta es: TRANSMISIÓN."},
  // ── GENERAL
  {cat:"General", q:"¿QUÉ SIGNIFICA LA SIGLA EPP?", opts:["ELEMENTOS PARA LA PROTECCIÓN","ESTADO DE PROTECCIÓN PERSONAL","ELEMENTOS DE PROTECCIÓN PERSONAL","ESTACIONAMIENTO PREVENTIVO PERSONAL"], ans:2, exp:"La respuesta correcta es: ELEMENTOS DE PROTECCIÓN PERSONAL."},
  // ── SEÑALES
  {cat:"Señales", q:"QUE SEÑALES PERTENECEN AL GRUPO DE LAS SEÑALES VERTICALES", opts:["PREVENTIVAS, INFORMATIVAS Y HORIZONTALES","PREVENTIVAS, REGLAMENTARIAS E INFORMATIVAS","PREVENTIVAS, REGLAMENTARIAS Y VERTICALES","PREVENTIVAS, INFORMATIVAS Y CONOS"], ans:1, exp:"La respuesta correcta es: PREVENTIVAS, REGLAMENTARIAS E INFORMATIVAS."},
  // ── PRIMEROS AUXILIOS
  {cat:"Primeros Auxilios", q:"¿CUAL ES LA FUNCIÓN DE LOS ELEMENTOS DE LA SEGURIDAD PASIVA?", opts:["MINIMIZAR EL IMPACTO Y CONSECUENCIAS DEL MISMO","MANTENER EL CONTROL DEL AUTOMOTOR","AMORTIGUAR LOS POSIBLES DAÑOS OCURRIDOS EN UN ACCIDENTE DE TRANSITO","A Y C SON VERDADERAS"], ans:3, exp:"La respuesta correcta es: A Y C SON VERDADERAS."},
  // ── GENERAL
  {cat:"General", q:"LA INSPECCIÓN PRE-OPERACIONAL DIARIA DEL VEHÍCULO AUTOMOTOR, SE DEBE REALIZAR PARA:", opts:["DARSE CUENTA DE CUANTO KILOMETRAJE HACE DE UN PUNTO A UN PUNTO","CERCIORARSE DE QUE EL AUTOMOTOR, ESTÁ EN PERFECTAS CONDICIONES","SABER SI LA GARANTÍA DEL AUTOMOTOR ESTÁ VIGENTE","NINGUNA DE LAS ANTERIORES"], ans:1, exp:"La respuesta correcta es: CERCIORARSE DE QUE EL AUTOMOTOR, ESTÁ EN PERFECTAS CONDICIONES."},
  // ── PRIMEROS AUXILIOS
  {cat:"Primeros Auxilios", q:"LOS ELEMENTOS QUE MINIMIZAN LAS LESIONES CERVICALES EN CASO DE UN ACCIDENTE DE TRÁNSITO SON:", opts:["SEGURIDAD ACTIVA","SEGURIDAD PASIVA","MANDOS SUPERIORES","ELEMENTOS DE SEGURIDAD"], ans:1, exp:"La respuesta correcta es: SEGURIDAD PASIVA."},
  // ── CONDUCCIÓN SEGURA
  {cat:"Conducción Segura", q:"CUANTOS SEGUNDOS DEBEN PASAR DESPUÉS DE DETERMINAR EL PUNTO DE REFERENCIA PARA TENER UNA DISTANCIA ADECUADA ENTRE SU VEHÍCULO Y QUE VA DELANTE:", opts:["CUATRO SEGUNDOS","TRES SEGUNDOS","SIETE SEGUNDOS","DOS SEGUNDOS"], ans:0, exp:"La respuesta correcta es: CUATRO SEGUNDOS."},
  // ── MECÁNICA
  {cat:"Mecánica", q:"QUE ES LO MÁS IMPORTANTE PARA EVITAR CHOCAR AL VEHÍCULO QUE VA ADELANTE", opts:["ASEGURARSE DE QUE SUS FRENOS SEAN EFICIENTES","CONDUCIR A UNA VELOCIDAD CONSTANTE","MANTENER UNA ADECUADA DISTANCIA DE SEPARACIÓN ENTRE LOS DOS VEHÍCULOS","TENER NEUMÁTICOS (LLANTAS) EN MUY BUEN ESTADO"], ans:2, exp:"La respuesta correcta es: MANTENER UNA ADECUADA DISTANCIA DE SEPARACIÓN ENTRE LOS DOS VEHÍCULOS."},
  // ── GENERAL
  {cat:"General", q:"EL ALTO CONSUMO DE COMBUSTIBLE SE DEBE A:", opts:["FALLAS EN EL SISTEMA DE DIRECCIÓN","ACELERACIONES EXCESIVAS","FRECUENTES FRENADAS","B Y C SON CIERTAS"], ans:1, exp:"La respuesta correcta es: ACELERACIONES EXCESIVAS."},
  // ── MECÁNICA
  {cat:"Mecánica", q:"PARA CONOCER EL NIVEL ADECUADO DEL ACEITE DE UN MOTOR, LA MEDIDA EN LA VARILLA DEBE ESTAR:", opts:["EN EL MÍNIMO",". EN LA MITAD","EN EL MÁXIMO","POR ENCIMA DEL MÁXIMO"], ans:2, exp:"La respuesta correcta es: EN EL MÁXIMO."},
  {cat:"Mecánica", q:"EL ACEITE DE UN AUTOMOTOR, SE DEBE REVISAR:", opts:["CON EL MOTOR ENCENDIDO","CON EL MOTOR APAGADO","CON EL VEHÍCULO LEVEMENTE INCLINADO","NINGUNA DE LAS ANTERIORES"], ans:1, exp:"La respuesta correcta es: CON EL MOTOR APAGADO."},
  {cat:"Mecánica", q:"LA INSPECCIÓN PREOPERACIONARIAL DIARIA DEL AUTOMOTOR, SE DEBE REALIZAR", opts:["SOLO CON EL MOTOR ENCENDIDO, EN TERRENO PLANO","SOLO CON EL MOTOR APAGADO, EN TERRENO PLANO","CON EL MOTOR APAGADO Y CON EL MOTOR ENCENDIDO EN TERRENO PLANO","NINGUNA APLICA"], ans:1, exp:"La respuesta correcta es: SOLO CON EL MOTOR APAGADO, EN TERRENO PLANO."},
  {cat:"Mecánica", q:"SI SE OBSERVA, DESGASTE EN LA PARTE EXTERNA DE UN NEUMÁTICO, ES PORQUE EL AUTOMOTOR TIENE UN PROBLEMAS DE:", opts:["FLEXIBILIDAD","BALANCEO","SUSPENSIÓN","ALINEACIÓN"], ans:3, exp:"La respuesta correcta es: ALINEACIÓN."},
  // ── SEÑALES
  {cat:"Señales", q:"MIENTRAS SE CONDUCE, UNO DE LOS NEUMÁTICOS TRASEROS DEL AUTOMOTOR SE REVIENTA, QUE ACCIÓN SE DEBE REALIZAR:", opts:["SELECCIONAR REVERSA PARA DETENER EL VEHÍCULO RÁPIDAMENTE","HACER UNA SEÑAL CON LAS LUCES DELANTERAS DEL AUTOMOTOR","DETENERSE LENTAMENTE A UN COSTADO DE LA VÍA","TODAS SON CORRECTAS"], ans:2, exp:"La respuesta correcta es: DETENERSE LENTAMENTE A UN COSTADO DE LA VÍA."},
  // ── MECÁNICA
  {cat:"Mecánica", q:"EN UN PAVIMENTO MOJADO, EL ESTADO DE LOS NEUMÁTICOS INFLUYE EN LA DISTANCIA DE FRENADO DEL VEHÍCULO:", opts:["NO, LA DISTANCIA DE FRENADO DEPENDE SOLAMENTE DE LA VELOCIDAD","SI, PORQUE A MAYOR DESGASTE DE LOS NEUMÁTICOS MAYOR ES LA DISTANCIA DE FRENADO","NO, PORQUE UNA VEZ SE ACTIVA EL FRENO LA DISTANCIA DE FRENADO DE UN VEHÍCULO ES SIEMPRE IGUAL","A Y C, SON CORRECTAS"], ans:1, exp:"La respuesta correcta es: SI, PORQUE A MAYOR DESGASTE DE LOS NEUMÁTICOS MAYOR ES LA DISTANCIA DE FRENADO."},
  {cat:"Mecánica", q:"¿CUÁL AFIRMACIÓN ES FALSA?", opts:["LOS GASES DE ESCAPE DE LOS VEHÍCULOS NO SON PELIGROSOS PARA LA SALUD DE LAS PERSONAS","LA BATERÍA MAL CARGADA HACE QUE EL VEHÍCULO TENGA PROBLEMAS PARA ARRANCAR","UNA TEMPERATURA DEL MOTOR DEMASIADO ALTA PUEDE DEBERSE A LA RUPTURA DE LA CORREA DE LA BOMBA DE AGUA","TODAS SON FALSAS"], ans:0, exp:"La respuesta correcta es: LOS GASES DE ESCAPE DE LOS VEHÍCULOS NO SON PELIGROSOS PARA LA SALUD DE LAS PERSONAS."},
  {cat:"Mecánica", q:"¿AL DESCENDER POR UNA PENDIENTE MUY LARGA, ¿QUÉ SE DEBE HACER PARA AYUDAR A CONTROLAR LA VELOCIDAD DEL VEHÍCULO?", opts:["SELECCIONAR UN CAMBIO BAJO Y EVITAR USAR LOS FRENOS","SELECCIONAR UN CAMBIO ALTO Y USAR LOS FRENOS CUIDADOSAMENTE","SELECCIONAR UN CAMBIO ALTO Y USAR LOS FRENOS FIRMEMENTE","SELECCIONAR UN CAMBIO BAJO Y USAR LOS FRENOS CUIDADOSAMENTE"], ans:3, exp:"La respuesta correcta es: SELECCIONAR UN CAMBIO BAJO Y USAR LOS FRENOS CUIDADOSAMENTE."},
  {cat:"Mecánica", q:"¿CUÁL VARIABLE INFLUYE EN LA DISTANCIA DE FRENADO?", opts:["EL ESTADO DE LOS FRENOS Y DE LOS NEUMÁTICOS","EL ALUMBRADO PÚBLICO","LAS CONDICIONES CLIMÁTICAS","A Y C, SON CORRECTAS"], ans:3, exp:"La respuesta correcta es: A Y C, SON CORRECTAS."},
  {cat:"Mecánica", q:"¿CUÁL ES UNA POSIBLE CAUSA DEL SOBRECALENTAMIENTO DEL MOTOR?", opts:["INSUFICIENTE PASO DE AGUA CALIENTE AL RADIADOR DE CALEFACCIÓN","BATERÍA CON CARGA BAJA","SISTEMA DE REFRIGERACIÓN OBSTRUIDO","BAJO NIVEL DE AGUA EN LA BATERÍA"], ans:2, exp:"La respuesta correcta es: SISTEMA DE REFRIGERACIÓN OBSTRUIDO."},
  {cat:"Mecánica", q:"¿EN UN AUTOMÓVIL SOBRE QUE RUEDAS ACTÚA EL FRENO DE SEGURIDAD O DE MANO?", opts:["SOBRE TODAS","SOBRE LAS DELANTERAS","SOBRE LAS TRASERAS","SOBRE UNA RUEDA DELANTERA Y OTRA TRASERA"], ans:2, exp:"La respuesta correcta es: SOBRE LAS TRASERAS."},
  {cat:"Mecánica", q:"ORIENTAR LAS RUEDAS DELANTERAS O DIRECTRICES PARA DIRIGIR EL VEHÍCULO SEGÚN LA VOLUNTAD DEL CONDUCTOR ES LA FUNCIÓN DEL SISTEMA DE:", opts:["SUSPENSIÓN","TRANSMISIÓN","DIRECCIÓN","FRENOS"], ans:2, exp:"La respuesta correcta es: DIRECCIÓN."},
  {cat:"Mecánica", q:"CUALES SON LAS TRES PARTES PRINCIPALES DEL MOTOR:", opts:["CULATA, BLOQUE Y CÁRTER","CAJA, DIRECCIÓN Y BLOQUE","ALTERNADOR, RADIADOR Y CULATA","ÁRBOL DE LEVA, BALANCINES Y CULATA"], ans:0, exp:"La respuesta correcta es: CULATA, BLOQUE Y CÁRTER."},
  {cat:"Mecánica", q:"¿CUAL ES EL ORDEN DE LOS CUATRO TIEMPOS DE COMBUSTIÓN DE UN MOTOR?", opts:["COMPRESIÓN, EXPLOSIÓN, ADMISIÓN, ESCAPE","EXPLOSIÓN, ADMISIÓN, COMPRESIÓN, ESCAPE","ADMISIÓN, COMPRESIÓN, EXPLOSIÓN, ESCAPE","ADMISIÓN, EXPLOSIÓN, ESCAPE, COMPRESIÓN"], ans:2, exp:"La respuesta correcta es: ADMISIÓN, COMPRESIÓN, EXPLOSIÓN, ESCAPE."},
  // ── GENERAL
  {cat:"General", q:"EL ENCARGADO DE GENERAR LA ENERGÍA SUFICIENTE EN EL CARRO PARA QUE FUNCIONE UN AUTOMOTOR Y MANTENGA CARGADA LA BATERÍA ES:", opts:["EL DISTRIBUIDOR","EL TERMOSTATO","EL ALTERNADOR","LA BOBINA DE ENCENDIDO"], ans:2, exp:"La respuesta correcta es: EL ALTERNADOR."},
  // ── DOCUMENTOS
  {cat:"Documentos", q:"LOS TRÁMITES PARA LA OBTENCIÓN, RENOVACIÓN  DE LA LICENCIA DE CONDUCCIÓN SE REALIZAN ANTE QUÉ ENTIDAD:", opts:["EL MINISTERIO DE TRANSPORTE","LOS ORGANISMOS DE TRÁNSITO DE LA LOCALIDAD","LAS ALCALDÍAS MUNICIPALES O DISTRITALES","LAS ESCUELAS DE CONDUCCIÓN"], ans:1, exp:"La respuesta correcta es: LOS ORGANISMOS DE TRÁNSITO DE LA LOCALIDAD."},
  // ── AUTORIDADES Y NORMAS
  {cat:"Autoridades y Normas", q:"DERECHO FUNDAMENTAL, QUE NOS BRINDA LA CONSTITUCIÓN POLÍTICA, COMO ACTOR DE TRÁNSITO EN LA SEGURIDAD VIAL.", opts:["LA CIRCULACIÓN DE LOS VEHÍCULOS CÓDIGO NACIONAL LEY 769 DEL 2002","LA LIBRE CIRCULACIÓN ART 24 CONSTITUCIÓN POLÍTICA DE COLOMBIA","CUMPLIMIENTO A LAS NORMAS ARTÍCULO 1 CÓDIGO NACIONAL","TODAS LAS ANTERIORES"], ans:1, exp:"La respuesta correcta es: LA LIBRE CIRCULACIÓN ART 24 CONSTITUCIÓN POLÍTICA DE COLOMBIA."},
  // ── GENERAL
  {cat:"General", q:"LAS LICENCIAS DE CONDUCCIÓN PARA VEHÍCULOS DE SERVICIO PÚBLICO(C1) TENDRÁN UNA VIGENCIA DE:", opts:["2 AÑOS","3 AÑOS","5 AÑOS","10 AÑOS"], ans:1, exp:"La respuesta correcta es: 3 AÑOS."},
  // ── DOCUMENTOS
  {cat:"Documentos", q:"EN COLOMBIA SE OTORGA LA LICENCIA DE CONDUCCIÓN POR PRIMERA VEZ PARA CONDUCIR VEHÍCULOS DE SERVICIO PARTICULAR (B1- A2) A QUIEN TENGA LA EDAD DE:", opts:["22 AÑOS CUMPLIDOS","20 AÑOS CUMPLIDOS","18 AÑOS CUMPLIDOS","16 AÑOS CUMPLIDOS"], ans:3, exp:"La respuesta correcta es: 16 AÑOS CUMPLIDOS."},
  // ── GENERAL
  {cat:"General", q:"¿PARA QUIÉN ES OBLIGATORIO EL USO DEL CINTURÓN DE SEGURIDAD?", opts:["SOLAMENTE PARA EL CONDUCTOR","SOLAMENTE PARA LOS QUE VAN EN LA PARTE ADELANTE","SOLAMENTE PARA LOS PASAJEROS","PARA TODOS LOS OCUPANTES DEL VEHÍCULO"], ans:3, exp:"La respuesta correcta es: PARA TODOS LOS OCUPANTES DEL VEHÍCULO."},
  // ── PRIMEROS AUXILIOS
  {cat:"Primeros Auxilios", q:"A QUE PERSONAS CUBRE EL SEGURO OBLIGATORIO DE ACCIDENTES DE TRANSITO (SOAT):", opts:["A TODAS LAS PERSONAS, SALVO EL CONDUCTOR CAUSANTE DEL ACCIDENTE","A TODAS LAS PERSONAS, SALVO EL PROPIETARIO DEL VEHÍCULO SI ESTE ES EL CAUSANTE DEL ACCIDENTE","A TODAS LAS PERSONAS INVOLUCRADAS EN EL ACCIDENTE DENTRO DE LAS CUANTÍAS ESTABLECIDAS","A TODAS LAS PERSONAS, SALVO SU TOMADOR"], ans:2, exp:"La respuesta correcta es: A TODAS LAS PERSONAS INVOLUCRADAS EN EL ACCIDENTE DENTRO DE LAS CUANTÍAS ESTABLECIDAS."},
  // ── GENERAL
  {cat:"General", q:"PRIORIDAD O PREFERENCIA QUE TIENE UNA VÍA O VEHÍCULO CON RESPECTO A OTRAS VÍAS U OTROS VEHÍCULOS, SE LE DENOMINA:", opts:["INTERSECCIÓN","GLORIETA","PRELACIÓN","POMPEYANO"], ans:2, exp:"La respuesta correcta es: PRELACIÓN."},
  // ── SEÑALES
  {cat:"Señales", q:"TODO CONDUCTOR ESTÁ OBLIGADO A UTILIZAR LAS SEÑALES DIRECCIONALES DE SU VEHÍCULO PARA:", opts:["CAMBIAR DE CARRIL","CAMBIAR DE CALZADA","REALIZAR UN GIRO","TODAS LAS ANTERIORES"], ans:3, exp:"La respuesta correcta es: TODAS LAS ANTERIORES."},
  // ── PRIMEROS AUXILIOS
  {cat:"Primeros Auxilios", q:"¿CUÁL? DE LAS SIGUIENTES CAUSAS SE PRESENTA CON MAYOR FRECUENCIA EN LOS ACCIDENTES DE TRÁNSITO:", opts:["LAS CONDICIONES CLIMÁTICAS","LOS ERRORES HUMANOS","EL ESTADO DE LAS VÍAS","LAS FALLAS MECÁNICAS"], ans:1, exp:"La respuesta correcta es: LOS ERRORES HUMANOS."},
  // ── SEÑALES
  {cat:"Señales", q:"SI OBSERVA QUE EL SEMÁFORO MUESTRA LA LUZ VERDE Y EN LA MISMA POSICIÓN SE ENCUENTRA UN AGENTE DE TRÁNSITO INDICANDO QUE SE DETENGA. ¿USTED A QUÉ SEÑAL LE DA PRIORIDAD?", opts:["AL SEMÁFORO","AL AGENTE DE TRÁNSITO","AL SEMÁFORO Y AL AGENTE AL MISMO TIEMPO","A NINGUNO"], ans:1, exp:"La respuesta correcta es: AL AGENTE DE TRÁNSITO."},
  {cat:"Señales", q:"SE PUEDE IDENTIFICAR UNA SEÑAL REGLAMENTARIA EN LA VÍA, POR:", opts:["SU COLOR AMARILLO EN EL FONDO Y NEGRO PARA LOS BORDES, SÍMBOLOS Y LETRAS","SU COLOR AMARILLO EN EL FONDO Y AZUL PARA LOS BORDES, SÍMBOLOS Y LETRAS NEGRAS","SU COLOR ROJO EN LAS ORILLAS, CON FONDO BLANCO Y SÍMBOLO Y LETRAS DE NEGRO","SU COLOR AZUL EN EL FONDO Y BLANCO PARA LOS BORDES, SÍMBOLOS Y LETRAS"], ans:2, exp:"La respuesta correcta es: SU COLOR ROJO EN LAS ORILLAS, CON FONDO BLANCO Y SÍMBOLO Y LETRAS DE NEGRO."},
  // ── GENERAL
  {cat:"General", q:"CUANDO DOS (2) O MÁS VEHÍCULOS TRANSITEN EN SENTIDO CONTRARIO POR UNA VÍA DE DOBLE SENTIDO DE TRÁNSITO E INTENTEN GIRAR AL MISMO LADO, LA PRELACIÓN LA TIENE:", opts:["EL QUE VA A GIRAR A LA IZQUIERDA","EL QUE SE ACERCA AL CRUCE POR LA DERECHA DEL OTRO","EL QUE SE ACERCA AL CRUCE POR LA IZQUIERDA DEL OTRO","EL QUE VA A GIRAR A LA DERECHA"], ans:3, exp:"La respuesta correcta es: EL QUE VA A GIRAR A LA DERECHA."},
  // ── CONDUCCIÓN SEGURA
  {cat:"Conducción Segura", q:"AL ADELANTAR A OTRO VEHÍCULO EN UNA INTERSECCIÓN, LO DEBE HACER A UNA VELOCIDAD DE:", opts:["30 K/PH","40 K/PH","50 K/PH","NINGUNA ES CIERTA"], ans:3, exp:"La respuesta correcta es: NINGUNA ES CIERTA."},
  {cat:"Conducción Segura", q:"AL CONDUCIR UN VEHÍCULO EN UNA CURVA, LA VELOCIDAD DEBE SER REDUCIDA:", opts:["ANTES DE ENTRAR A ELLA","CUANDO LA VA RECORRIENDO","CUANDO YA HA PASADO LA MITAD DE ELLA","CUANDO VA SALIENDO DE ELLA"], ans:0, exp:"La respuesta correcta es: ANTES DE ENTRAR A ELLA."},
  // ── ALCOHOL Y SUSTANCIAS
  {cat:"Alcohol y Sustancias", q:"EL CONSUMO DE UNA PEQUEÑA DOSIS DE ALCOHOL LO PUEDE LLEVAR A:", opts:["UN MODO DE CONDUCIR ARRIESGADO","REACCIONES RETARDADAS","UNA DISMINUCIÓN EN SUS CAPACIDADES","TODAS SON CIERTAS"], ans:3, exp:"La respuesta correcta es: TODAS SON CIERTAS."},
  // ── PEATONES Y CICLISTAS
  {cat:"Peatones y Ciclistas", q:"CONDUCTA PROHIBIDA PARA LOS PEATONES:", opts:["DESPLAZARSE ENTRE VEHÍCULOS, CUANDO ESTÁ EL SEMÁFORO EN ROJO","INVADIR LA ZONA DESTINADA AL TRÁNSITO DE VEHÍCULOS CON MONOPATÍN, PATINETAS O PATINES","CORRER PARA CRUZAR LA VÍA","TODAS LAS ANTERIORES"], ans:3, exp:"La respuesta correcta es: TODAS LAS ANTERIORES."},
  // ── ALCOHOL Y SUSTANCIAS
  {cat:"Alcohol y Sustancias", q:"LOS EFECTOS NEGATIVOS AL INGERIR BEBIDAS ALCOHÓLICAS, AL MOMENTO DE CONDUCIR, ALCANZAN SU PUNTO MÁXIMO EN:", opts:["INMEDIATAMENTE","APROXIMADAMENTE A LA HORA","APROXIMADAMENTE A LAS 2 HORAS","APROXIMADAMENTE A LAS 3 HORAS"], ans:1, exp:"La respuesta correcta es: APROXIMADAMENTE A LA HORA."},
  // ── GENERAL
  {cat:"General", q:"¿CUÁL AFIRMACIÓN ES FALSA?", opts:["EL ESTRÉS DE LOS DEMÁS CONDUCTORES, ES UN DETONANTE DE SU PROPIO ESTRÉS","UN ESTRÉS MODERADO PUEDE CONTRIBUIR A MEJORAR SU RENDIMIENTO","UN CONDUCTOR MUY ESTRESADO PUEDE TENER REACCIONES DE PÁNICO","EL ESTRÉS NO INFLUYE EN ABSOLUTO EN LOS ACTOS DE UN CONDUCTOR"], ans:3, exp:"La respuesta correcta es: EL ESTRÉS NO INFLUYE EN ABSOLUTO EN LOS ACTOS DE UN CONDUCTOR."},
  // ── MOTOCICLISTAS
  {cat:"Motociclistas", q:"DENTRO DE LA LEY 769 DE 2002, LAS NORMAS ESPECÍFICAS PARA MOTOCICLETAS, MOTO CICLOS Y MOTO TRICICLOS, ESTÁN ESTABLECIDAS EN EL:", opts:["ARTICULO 66","ARTICULO 76","ARTICULO 86","ARTÍCULO 96"], ans:3, exp:"La respuesta correcta es: ARTÍCULO 96."},
  {cat:"Motociclistas", q:"EN UNA MOTOCICLETA PARA GARANTIZA UN BUEN AGARRE DE LOS NEUMÁTICOS AL MOMENTO DE FRENAR, SIN QUE SE PIERDA EL EQUILIBRIO, SE DEBE APLICAR LA PROPORCIÓN:", opts:["60 % EN EL FRENO DELANTERO Y 40% EN EL FRENO TRASERO","70 % EN EL FRENO DELANTERO Y 30% EN EL FRENO TRASERO","30 % EN EL FRENO DELANTERO Y 70% EN EL FRENO TRASERO","40 % EN EL FRENO DELANTERO Y 60% EN EL FRENO TRASERO"], ans:2, exp:"La respuesta correcta es: 30 % EN EL FRENO DELANTERO Y 70% EN EL FRENO TRASERO."},
  {cat:"Motociclistas", q:"ELEMENTO QUE NO ES DE USO OBLIGATORIO MIENTRAS SE CONDUCE UNA MOTOCICLETA DE DÍA:", opts:["PRENDA REFLECTIVA","CASCO REGLAMENTARIO","LUCES DELANTERAS Y TRASERAS ENCENDIDAS","A Y C SON CIERTAS"], ans:0, exp:"La respuesta correcta es: PRENDA REFLECTIVA."},
  {cat:"Motociclistas", q:"ELEMENTO QUE DE NO EMPLEARLO MIENTRAS SE CONDUCE UNA MOTOCICLETA, DARÁ INMOVILIZACIÓN DEL VEHÍCULO:", opts:["TRAJE DE PROTECCIÓN","CASCO REGLAMENTARIO","ZAPATOS","GUANTES"], ans:1, exp:"La respuesta correcta es: CASCO REGLAMENTARIO."},
  // ── PRIMEROS AUXILIOS
  {cat:"Primeros Auxilios", q:"EN UN ACCIDENTE DE TRÁNSITO, CUAL ES LA PARTE DEL CUERPO MÁS VULNERABLE PARA UN MOTOCICLISTA Y SU ACOMPAÑANTE:", opts:["LA CABEZA","LAS MANOS","LA CADERA","LAS PIERNAS"], ans:0, exp:"La respuesta correcta es: LA CABEZA."},
  // ── MOTOCICLISTAS
  {cat:"Motociclistas", q:"LAS MOTOCICLETAS Y SIMILARES, SE SOMETERÁN A LA PRIMERA REVISIÓN TÉCNICO-MECÁNICA Y DE EMISIONES CONTAMINANTES A PARTIR DEL:", opts:["PRIMER AÑO","SEGUNDO AÑO","TERCER AÑO","SEXTO AÑO"], ans:1, exp:"La respuesta correcta es: SEGUNDO AÑO."},
  {cat:"Motociclistas", q:"LA CATEGORÍA DE LA LICENCIA DE CONDUCCIÓN QUE HABILITA A UNA PERSONA A CONDUCIR UNA MOTOCICLETA HASTA 125 CM3, ES:", opts:["A1","A2","A3","A4"], ans:0, exp:"La respuesta correcta es: A1."},
  // ── GENERAL
  {cat:"General", q:"CONJUNTO DE ELEMENTOS QUE PROPORCIONAN SOPORTE A TODAS LAS PARTES DEL AUTOMOTOR (ESQUELETO DE LA MOTO):", opts:["CHASIS","BASTIDOR","CARROCERÍA","CABINA"], ans:0, exp:"La respuesta correcta es: CHASIS."},
  // ── PRIMEROS AUXILIOS
  {cat:"Primeros Auxilios", q:"DE QUÉ LE ADVIERTE ESTA SEÑAL?", opts:["CONSERVACIÓN DEL ESPACIAMIENTO","ZONA DE ALTO RIESGO DE ACCIDENTE","ZONA DE ALTO RIESGO DE TURBULENCIA","ZONA DE ALTO RIESGO DE DERRUMBES"], ans:1, exp:"La respuesta correcta es: ZONA DE ALTO RIESGO DE ACCIDENTE.", img:"./imgs/preguntas/q89_riesgo_accidente.png"},
  // ── SEÑALES
  {cat:"Señales", q:"¿DE QUÉ LE ADVIERTE ESTA SEÑAL?", opts:["NO BLOQUEAR CRUCE EN EL TRAFICO","NO BLOQUEAR CRUCE EN EL ESTACIONAMIENTO","NO BLOQUEAR CRUCE EN LA BAHÍA","NO BLOQUEAR CRUCE EN LA INTERSECCIÓN"], ans:3, exp:"La respuesta correcta es: NO BLOQUEAR CRUCE EN LA INTERSECCIÓN.", img:"./imgs/preguntas/q90_no_bloquear_cruce.png"},
  {cat:"Señales", q:"¿DE QUÉ LE ADVIERTE ESTA SEÑAL?", opts:["SUPERFICIE INESTABLE","SUPERFICIE DESLIZANTE","SUPERFICIE RODANTE","SUPERFICIE MOVEDIZA"], ans:1, exp:"La respuesta correcta es: SUPERFICIE DESLIZANTE.", img:"./imgs/preguntas/q91_superficie_deslizante.png"},
  // ── GENERAL
  {cat:"General", q:"¿EN QUÉ SITUACIÓN SE DEBE HACER USO DE LA BOCINA DE UN AUTOMOTOR?", opts:["EN NINGÚN MOMENTO SE DEBE HACER EL USO DE ESTE MIENTRAS EL VEHÍCULO ESTE EN MOVIMIENTO","PARA SALUDAR A OTROS USUARIOS DE LA VÍA","PARA TRATAR DE PREVENIR A OTROS USUARIOS DE LA VÍA, SOBRE UN PELIGRO","PARA MANIFESTAR EL DISGUSTO A OTROS USUARIOS DE LA VÍA"], ans:2, exp:"La respuesta correcta es: PARA TRATAR DE PREVENIR A OTROS USUARIOS DE LA VÍA, SOBRE UN PELIGRO."},
  // ── CONDUCCIÓN SEGURA
  {cat:"Conducción Segura", q:"MIENTRAS SE ESTÁ CONDUCIENDO Y SE PIERDE EL CONTROL DEL AUTOMOTOR. ¿QUÉ SE DEBE HACER?", opts:["CAMBIAR A UNA MARCHA MÁS BAJA","FRENAR LEVEMENTE PARA REDUCIR LA VELOCIDAD","DESPLAZAR EL AUTOMOTOR LO MÁS CERCA DEL BORDE DE LA CALZADA","LIBERAR LA PRESIÓN DEL VOLANTE"], ans:2, exp:"La respuesta correcta es: DESPLAZAR EL AUTOMOTOR LO MÁS CERCA DEL BORDE DE LA CALZADA."},
  // ── DOCUMENTOS
  {cat:"Documentos", q:"EN UN CENTRO DE ENSEÑANZA DE AUTOMOVILISMO, UN APRENDIZ DESPUÉS DE HABER TERMINADO LA INSTRUCCIÓN EN TÉCNICAS DE CONDUCCIÓN, OBTENDRÁ:", opts:["LA LICENCIA DE CONDUCCIÓN","UN CERTIFICADO DE CAPACITACIÓN","LA LICENCIA DE TRANSITO","A Y C SON CIERTAS"], ans:1, exp:"La respuesta correcta es: UN CERTIFICADO DE CAPACITACIÓN."},
  // ── SEÑALES
  {cat:"Señales", q:"¿DE QUÉ LE ADVIERTE ESTA SEÑAL?", opts:["PROHIBIDO PARQUEAR","QUE PUEDO PARQUEAR Y DETENERME POR 20 MINUTOS","QUE NO DEBO PARQUEAR NI DETENERME","PUEDO ESTACIONAR Y DETENERME POR UN TIEMPO DETERMINADO"], ans:2, exp:"La respuesta correcta es: QUE NO DEBO PARQUEAR NI DETENERME.", img:"./imgs/preguntas/q95_no_parquear.png"},
  {cat:"Señales", q:"LAS SEÑALES DE TRÁNSITO QUE REGLAMENTAN LIMITACIONES, PROHIBICIONES O RESTRICCIONES, ADVIERTEN DE PELIGROS E INFORMAN A CERCA DE RUTAS, DIRECCIONES, DESTINOS Y SITIOS DE INTERÉS, SON:", opts:["SEÑALES REGLAMENTARIAS","SEÑALES VERTICALES","SEÑALES INFORMATIVAS","SEÑALES PREVENTIVAS"], ans:1, exp:"La respuesta correcta es: SEÑALES VERTICALES."},
  {cat:"Señales", q:"¿DE QUÉ LE ADVIERTE ESTA SEÑAL?", opts:["QUE SE DEBE REALIZAR LA CURVA A LA IZQUIERDA SOLAMENTE","QUE SE DEBE REALIZAR EL GIRO A LA DERECHA SOLAMENTE","QUE SE DEBE REALIZAR EL GIRO A LA DERECHA E IZQUIERDA SOLAMENTE","QUE ESTÁ PROHIBIDO EL GIRO A LA DERECHA"], ans:1, exp:"La respuesta correcta es: QUE SE DEBE REALIZAR EL GIRO A LA DERECHA SOLAMENTE.", img:"./imgs/preguntas/q97_giro_derecha.png"},
  {cat:"Señales", q:"¿DE QUÉ LE ADVIERTE ESTA SEÑAL?", opts:["LA VELOCIDAD MÁXIMA PERMITIDA PARA LA CIRCULACIÓN ES DE 30 KPH","LA VELOCIDAD MÍNIMA PERMITIDA PARA LA CIRCULACIÓN ES DE 30 KPH","EL ESTACIONAMIENTO EN ESA ZONA MÍNIMO ES DE 30 MINUTOS","EL ESTACIONAMIENTO EN ESA ZONA, MÁXIMO, ES DE 30 MINUTOS"], ans:1, exp:"La respuesta correcta es: LA VELOCIDAD MÍNIMA PERMITIDA PARA LA CIRCULACIÓN ES DE 30 KPH.", img:"./imgs/preguntas/q98_velocidad_minima.png"},
  // ── GENERAL
  {cat:"General", q:"¿CUÁL ES LA SEPARACIÓN MÍNIMA ENTRE DOS VEHÍCULOS QUE CIRCULAN UNO DETRÁS DEL OTRO A 30 KILÓMETROS POR HORA?", opts:["6 METROS","8 METROS","10 METROS","12 METROS"], ans:2, exp:"La respuesta correcta es: 10 METROS."},
  // ── PRIMEROS AUXILIOS
  {cat:"Primeros Auxilios", q:"¿QUÉ SIGNIFICA LA LÍNEA AMARILLA CONTINUA EN EL CENTRO DE UNA VÍA?", opts:["QUE EL ASFALTO ESTÁ EN MAL ESTADO","DOBLE SENTIDO DE CIRCULACIÓN Y NO SE PUEDE ADELANTAR","SE USA PARA DIVIDIR LOS SENTIDOS DE CIRCULACIÓN","QUE SE PUEDE ADELANTAR Y HAY RIEGO DE ACCIDENTABILIDAD"], ans:1, exp:"La respuesta correcta es: DOBLE SENTIDO DE CIRCULACIÓN Y NO SE PUEDE ADELANTAR."},
  // ── MECÁNICA
  {cat:"Mecánica", q:"CUANDO POR EL TUBO DE ESCAPE SALE HUMO \"AZUL,\" SIGNIFICA QUE EL VEHÍCULO ESTÁ:", opts:["EL MOTOR SE ENCUENTRA MAL SINCRONIZADO","EL MOTOR ESTA FUERA DEL PUNTO DEL ENCENDIDO","EL MOTOR ESTÁ QUEMANDO ACEITE","EL MOTOR ESTÁ QUEMANDO COMBUSTIBLE"], ans:2, exp:"La respuesta correcta es: EL MOTOR ESTÁ QUEMANDO ACEITE."},
  {cat:"Mecánica", q:"¿EN QUÉ FORMA SE DEBE ESTACIONAR EL AUTOMOTOR EN BAJADA?", opts:["SELECCIONAR NEUTRO EN LA CAJA DE VELOCIDADES, FRENO DE MANO Y LAS RUEDAS DELANTERAS GIRADAS HACIA LA ACERA","SELECCIONAR PRIMERA EN LA CAJA DE VELOCIDADES, FRENO DE MANO Y LAS RUEDAS DELANTERAS GIRADAS HACIA LA ACERA","SELECCIONAR REVERSA EN LA CAJA DE VELOCIDADES, FRENO DE MANO Y LAS RUEDAS DELANTERAS GIRADAS HACIA LA ACERA","SELECCIONAR QUINTA EN LA CAJA DE VELOCIDADES, FRENO DE MANO Y LAS RUEDAS DELANTERAS GIRADAS HACIA LA ACERA"], ans:2, exp:"La respuesta correcta es: SELECCIONAR REVERSA EN LA CAJA DE VELOCIDADES, FRENO DE MANO Y LAS RUEDAS DELANTERAS GIRADAS HACIA LA ACERA."},
  // ── PEATONES Y CICLISTAS
  {cat:"Peatones y Ciclistas", q:"SEGÚN LA LEY 769 DE 2002, ELEMENTOS PARA REGULAR Y ORDENAR EL TRÁNSITO SON:", opts:["LOS SEMÁFOROS PARA CONTROL DE VEHÍCULOS","LOS SEMÁFOROS ESPECIALES","LOS SEMÁFOROS PEATONALES","TODAS SON CIERTAS"], ans:3, exp:"La respuesta correcta es: TODAS SON CIERTAS."},
  // ── SEÑALES
  {cat:"Señales", q:"EL CONDUCTOR DEBE UTILIZAR LA SEÑAL INTERMITENTE DE PELIGRO:", opts:["CUANDO EL VEHÍCULO PRESENTA UNA AVERÍA Y SE ESTA MOVILIZANDO","CUANDO ESTÁ SIENDO LLEVADO EN CAMIÓN TIPO CAMABAJA","CUANDO ESTE OBSTACULIZANDO EL PASO","TODAS SON CIERTAS"], ans:0, exp:"La respuesta correcta es: CUANDO EL VEHÍCULO PRESENTA UNA AVERÍA Y SE ESTA MOVILIZANDO."},
  // ── GENERAL
  {cat:"General", q:"EL VOLANTE DE DIRECCIÓN, EN UN AUTOMOTOR PERMITE:", opts:["SUAVIZAR SU RECORRIDO","DIRIGIR Y MODIFICAR SU TRAYECTORIA","ATOMIZAR EL COMBUSTIBLE","A Y B SON CIERTAS"], ans:1, exp:"La respuesta correcta es: DIRIGIR Y MODIFICAR SU TRAYECTORIA."},
  {cat:"General", q:"CUÁL DE LOS SIGUIENTES PROCESOS HACE PARTE DEL SISTEMA DE COMBUSTIÓN?", opts:["EXPLOSIÓN","GOLPETEO","GOTEO","NINGUNA DE las anteriores"], ans:0, exp:"La respuesta correcta es: EXPLOSIÓN."},
  // ── MOTOCICLISTAS
  {cat:"Motociclistas", q:"CUANTOS FRENOS TIENE UNA MOTOCICLETA:", opts:["1","2","3","4"], ans:1, exp:"La respuesta correcta es: 2."},
  // ── GENERAL
  {cat:"General", q:"CUÁLES SON LOS 4 TIPOS DE DISTRACCIÓN EN LA CONDUCCIÓN.", opts:["AUDITIVA, MANUAL, PSICOLÓGICA Y MENTAL","COGNITIVA, AUDITIVA, MENTAL Y POR RUIDO","VISUAL, AUDITIVA, MANUAL Y COGNITIVA","TODAS LAS ANTERIORES"], ans:2, exp:"La respuesta correcta es: VISUAL, AUDITIVA, MANUAL Y COGNITIVA."},
  // ── DOCUMENTOS
  {cat:"Documentos", q:"DOCUMENTOS OBLIGATORIOS QUE SE DEBE PORTAR AL MOMENTO DE TRANSITAR EN UN VEHÍCULO", opts:["LICENCIA DE TRANSITO, SOAT Y RTM","LICENCIA DE CONDUCCIÓN Y CEDULA","LICENCIA DE CONDUCCIÓN Y TARJETA DE PROPIEDAD","A Y B SON CORRECTAS"], ans:2, exp:"La respuesta correcta es: LICENCIA DE CONDUCCIÓN Y TARJETA DE PROPIEDAD."},
  // ── INFRACCIONES
  {cat:"Infracciones", q:"DE QUÉ FORMA SE DIVIDEN LAS INFRACCIONES DE TRANSITO", opts:["POR NÚMEROS","POR LETRAS","POR NÚMEROS ROMANOS","NINGUNA DE las anteriores"], ans:1, exp:"La respuesta correcta es: POR LETRAS."},
  {cat:"Infracciones", q:"UN AGENTE DE TRÁNSITO ME PUEDE REALIZAR UNA INFRACCIÓN ASÍ EL PROCEDIMIENTO ESTE MAL HECHO", opts:["NO ME LA PUEDE REALIZAR","SI ME LA PUEDE REALIZAR","SI ES POLICÍA DE CARRETERA SI","SOLAMENTE SI HAY PUESTO DE CONTROL"], ans:1, exp:"La respuesta correcta es: SI ME LA PUEDE REALIZAR."},
  {cat:"Infracciones", q:"EN QUÉ SITUACIÓN ME PUEDE REALIZAR UNA INFRACCIÓN UN AGENTE DE TRANSITO", opts:["CUANDO EL QUIERA YA QUE ES UNA AUTORIDAD","EN UN PUESTO DE CONTROL O CUANDO ESTE COMETIENDO UNA INFRACCIÓN","SOLAMENTE EN EL CENTRO DE LA CIUDAD","NINGUNA DE las anteriores"], ans:1, exp:"La respuesta correcta es: EN UN PUESTO DE CONTROL O CUANDO ESTE COMETIENDO UNA INFRACCIÓN."},
  // ── ALCOHOL Y SUSTANCIAS
  {cat:"Alcohol y Sustancias", q:"CUANTOS GRADOS DE ALCOHOLEMIA EXISTEN?", opts:["1","2","3","4"], ans:3, exp:"La respuesta correcta es: 4."},
  {cat:"Alcohol y Sustancias", q:"CUÁLES SON LOS GRADOS DE ALCOHOLEMIA", opts:["GRADO TIPO 1,2,3 Y 4","GRADO TIPO 0, 1,2 Y 3","GRADO TIPO A, B, C Y D","NINGUNO DE ESTOS"], ans:1, exp:"La respuesta correcta es: GRADO TIPO 0, 1,2 Y 3."},
  {cat:"Alcohol y Sustancias", q:"QUE OTRAS SUSTANCIAS APARTE DEL ALCOHOL AFECTAN EN LA CONDUCCIÓN", opts:["LOS JUGOS NATURALES Y DROGAS ILÍCITAS","SOLAMENTE EL ALCOHOL","DROGAS ILÍCITAS Y ALGUNOS MEDICAMENTOS","ALGUNOS MEDICAMENTOS"], ans:2, exp:"La respuesta correcta es: DROGAS ILÍCITAS Y ALGUNOS MEDICAMENTOS."},
  {cat:"Alcohol y Sustancias", q:"CUANTOS TIPOS DE COMPARENDOS EXISTEN POR CADA GRADO DE ALCOHOLEMIA", opts:["1 TIPO DE COMPARENDO","2 TIPOS DE COMPARENDO","3 TIPOS DE COMPARENDO","4 TIPOS DE COMPARENDO"], ans:2, exp:"La respuesta correcta es: 3 TIPOS DE COMPARENDO."},
  {cat:"Alcohol y Sustancias", q:"CUANTO ES EL VALOR DEL COMPARENDO POR NEGARSE A REALIZAR LA PRUEBA DE ALCOHOLEMIA", opts:["90 SMLDV ($ 3.136.792)","180 SMDLV ($ 6.273.583)","1440 SMDLV ($ 54.961.860)","360 SMDLV ($ 12.546.742)"], ans:2, exp:"La respuesta correcta es: 1440 SMDLV ($ 54.961.860)."},
  // ── DOCUMENTOS
  {cat:"Documentos", q:"QUE CATEGORÍAS EXISTEN EN LA LICENCIA DE CONDUCCIÓN TIPO A (MOTO)", opts:["1 SOLA CATEGORÍA QUE ES A2","3 CATEGORÍAS QUE ES A1, A2 Y A3","2 CATEGORÍAS QUE ES A1 Y A2","4 CATEGORÍAS QUE ES A1, A2, A3 Y A4"], ans:2, exp:"La respuesta correcta es: 2 CATEGORÍAS QUE ES A1 Y A2."},
  {cat:"Documentos", q:"A PARTIR DE QUÉ EDAD PUEDO SACAR LA LICENCIA DE CONDUCCIÓN TIPO C1", opts:["16 AÑOS","17 AÑOS","18 AÑOS","19 AÑOS"], ans:2, exp:"La respuesta correcta es: 18 AÑOS."},
  // ── SEÑALES
  {cat:"Señales", q:"EN QUE ARTÍCULO DEL CÓDIGO NACIONAL DE TRÁNSITO ME INDICA QUE EL GIRO A LA DERECHA ES PERMITIDO CUANDO EL SEMÁFORO ESTA EN ROJO", opts:["ARTICULO 148","ARTICULO 67","ARTICULO 22","ARTICULO 118"], ans:3, exp:"La respuesta correcta es: ARTICULO 118."},
  // ── AUTORIDADES Y NORMAS
  {cat:"Autoridades y Normas", q:"LEY QUE RIGÜE EL CONDIGO NACIONAL DE TRANSITO", opts:["LEY 1500 DEL 2009","LEY 769 DEL 2002","LEY 171 DEL 2010","LEY 1079 DEL 2005"], ans:1, exp:"La respuesta correcta es: LEY 769 DEL 2002."},
  // ── SEÑALES
  {cat:"Señales", q:"QUE SON LAS SEÑALES TRANSITORIAS", opts:["SEÑALES QUE SE ENCUENTRAN POR UN TIEMPO DETERMINADO","SEÑALES QUE ESTÁN MIENTRAS HAY UNA CONSTRUCCIÓN O ARREGLO DE LA VÍA","SEÑALES QUE LAS COMPONEN LAMINAS, CONOS, VALLAS Y DEMÁS ELEMENTOS","TODAS LAS ANTERIORES"], ans:3, exp:"La respuesta correcta es: TODAS LAS ANTERIORES."},
  // ── GENERAL
  {cat:"General", q:"AL MOMENTO DE CIRCULAR POR UNA GLORIETA QUIEN LLEVA LA VÍA", opts:["EL VEHÍCULO QUE SE ENCUENTRA INGRESANDO A LA GLORIETA","EL VEHÍCULO QUE SE ENCUENTRA EN CIRCULACIÓN POR LA GLORIETA","EL VEHÍCULO MÁS GRANDE LLEVA LA VÍA","CUALQUIERA DE LOS DOS PUEDE LLEVAR LA VÍA"], ans:1, exp:"La respuesta correcta es: EL VEHÍCULO QUE SE ENCUENTRA EN CIRCULACIÓN POR LA GLORIETA."},
  // ── MECÁNICA
  {cat:"Mecánica", q:"CUALES SON LAS 3 PARTES PRINCIPALES DE UN MOTOR", opts:["CIGÜEÑAL, BUJÍA Y CARTER","CARTER, CILINDRO Y PISTÓN","CARTER, BLOQUE Y CULATA","ALTERNADOR, CARTER Y PISTÓN"], ans:2, exp:"La respuesta correcta es: CARTER, BLOQUE Y CULATA."},
  {cat:"Mecánica", q:"A CUANTOS KILÓMETROS ES RECOMENDABLE REALIZAR EL CAMBIO DE ACEITE DE UNA MOTO", opts:["2000 KILÓMETROS","1500 KILÓMETROS","1000 KILÓMETROS","2500 KILÓMETROS"], ans:1, exp:"La respuesta correcta es: 1500 KILÓMETROS."},
  {cat:"Mecánica", q:"PROFUNDIDAD MÍNIMA PERMITIDA QUE PUEDE TENER UNA LLANTA DE UN AUTOMOVIL", opts:["1,6 MM","2 MM","1,8 MM","3 MM"], ans:0, exp:"La respuesta correcta es: 1,6 MM."},
  // ── GENERAL
  {cat:"General", q:"CUÁLES SON LAS PARTES QUE CONFORMAN UN KIT DE ARRASTRE", opts:["CADENA Y GUAYA","CADENA, RIN Y PISTÓN","CADENA, PLATO Y PIÑÓN DE ARRASTRE","CADENA Y PIÑÓN DE ARRASTRE"], ans:2, exp:"La respuesta correcta es: CADENA, PLATO Y PIÑÓN DE ARRASTRE."},
  {cat:"General", q:"QUE SIGNIFICA CUANDO LA LÍNEA DEL CENTRO EN LA VÍA ES DE COLOR BLANCO", opts:["DOBLE SENTIDO DE CIRCULACIÓN","UN SOLO SENTIDO DE CIRCULACIÓN","QUE NO SE PUEDE ADELANTAR","QUE SE PUEDE ADELANTAR"], ans:1, exp:"La respuesta correcta es: UN SOLO SENTIDO DE CIRCULACIÓN."},
  // ── SEÑALES
  {cat:"Señales", q:"COMO SE LLAMA LA SIGUIENTE SEÑAL", opts:["CEDA EL PASO","PREVENTIVA","PREVENCIÓN DE CEDA EL PASO","PREVENTIVA Y REGLAMENTARIA"], ans:2, exp:"La respuesta correcta es: PREVENCIÓN DE CEDA EL PASO.", img:"./imgs/preguntas/q129_ceda_el_paso.png"},
  // ── PEATONES Y CICLISTAS
  {cat:"Peatones y Ciclistas", q:"COMO SE LLAMA EL CUADRO CON UNA X QUE SE ENCUENTRA EN LAS INTERCESIONES", opts:["CUADRO DE BLOQUEO","CUADRO DE CRUCE DE PEATONES","CUADRO DE PROHIBIDO EL CRUCE DE PEATONES","CUADRO ANTIBLOQUEO"], ans:3, exp:"La respuesta correcta es: CUADRO ANTIBLOQUEO.", img:"./imgs/preguntas/q130_cuadro_antibloqueo.png"},
  // ── PRIMEROS AUXILIOS
  {cat:"Primeros Auxilios", q:"CUÁL DE LOS SIGUIENTES LÍQUIDOS AL LLEGAR A UN NIVEL BAJO PUEDE OCASIONAR ACCIDENTES", opts:["LÍQUIDO DE FRENOS","LIQUIDO ANTICONGELANTE","LIQUIDO REFRIGERANTE","LIQUIDO DE BATERÍA"], ans:0, exp:"La respuesta correcta es: LÍQUIDO DE FRENOS."},
  // ── DOCUMENTOS
  {cat:"Documentos", q:"CUANTO ES EL VALOR DE LA INFRACCIÓN D01(GUIAR UN VEHÍCULO SIN HABER OBTENIDO LA LICENCIA DE CONDUCCIÓN CORRESPONDIENTE)", opts:["8 SMDLV","15 SMDLV","30 SMDLV","45 SMDLV"], ans:2, exp:"La respuesta correcta es: 30 SMDLV."},
  {cat:"Documentos", q:"CUANTO ES EL VALOR DE LA INFRACCIÓN B02 (POR TENER LA LICENCIA DE CONDUCCIÓN VENCIDA)", opts:["8 SMDLV","15 SMDLV","30 SMDLV","45 SMDLV"], ans:0, exp:"La respuesta correcta es: 8 SMDLV."},
  // ── MECÁNICA
  {cat:"Mecánica", q:"CUANTOS LÍQUIDOS TRAE EL CARRO EN LA PARTE DEL MOTOR", opts:["TRAE 4 LÍQUIDOS","TRAE 5 LÍQUIDOS","DEPENDIENDO DEL AUTOMÓVIL PUEDE TRAER 4 O 5 LÍQUIDOS","EL VEHÍCULO TRAE 6 LÍQUIDOS TENIENDO EN CUENTA EL DE FRENOS"], ans:2, exp:"La respuesta correcta es: DEPENDIENDO DEL AUTOMÓVIL PUEDE TRAER 4 O 5 LÍQUIDOS."},
  {cat:"Mecánica", q:"COMO SE LLAMA EL ELEMENTO QUE PUEDE UTILIZAR LA AUTORIDAD PARA MEDIR EL GRABADO DE UNA LLANTA", opts:["UNDIMETRO","PROFUNDIMETRO","GRAVÍMETRO","NINGUNA DE LAS ANTERIORES"], ans:1, exp:"La respuesta correcta es: PROFUNDIMETRO."},
  // ── GENERAL
  {cat:"General", q:"CUANTOS ELEMENTOS COMPONEN EL KIT DE CARRETERA DE UN CARRO", opts:["8 ELEMENTOS","9 ELEMENTOS","10 ELEMENTOS","11 ELEMENTOS"], ans:1, exp:"La respuesta correcta es: 9 ELEMENTOS."},
  // ── MOTOCICLISTAS
  {cat:"Motociclistas", q:"DE QUÉ COLOR DEBE SER LA VISERA DE UN CASCO AL MOMENTO DE CIRCULAR POR LAS VÍAS", opts:["TRANSPARENTE","NEGRO O TIPO ESPEJO","NO ES NECESARIO LLEVAR VISERA","CUALQUIER COLOR, NO HAY UNO DETERMINADO"], ans:3, exp:"La respuesta correcta es: CUALQUIER COLOR, NO HAY UNO DETERMINADO."},
  // ── SEÑALES
  {cat:"Señales", q:"AL MOMENTO DE QUE UN AGENTE DE TRÁNSITO ME SOLICITA PARQUEARME EN UNA SEÑAL DE PROHIBIDO PARQUEAR QUE DEBO HACER", opts:["NO DEBO PARQUEARME YA QUE LA SEÑAL ME LO ESTÁ PROHIBIENDO","PUEDO PARQUEARME DURANTE UN TIEMPO DETERMINADO QUE ME LO PERMITE LA SEÑAL","ME DEBO PARQUEAR YA QUE LA AUTORIDAD DE TRANSITO ESTA POR ENCIMA EN LA JERARQUÍA DE LAS SEÑALES DE TRANSITO","NO DEBO PARAR YA QUE EL AGENTE DE TRÁNSITO ESTÁ EN UN LUGAR NO PERMITIDO PARA PARQUEAR"], ans:2, exp:"La respuesta correcta es: ME DEBO PARQUEAR YA QUE LA AUTORIDAD DE TRANSITO ESTA POR ENCIMA EN LA JERARQUÍA DE LAS SEÑALES DE TRANSITO."},
  // ── MOTOCICLISTAS
  {cat:"Motociclistas", q:"EL TRAJE DE PROTECCIÓN ES UN ELEMENTO OBLIGATORIO QUE DEBO PORTAR AL MOMENTO DE CONDUCIR MI MOTOCICLETA", opts:["SI ES OBLIGATORIO EN TODO MOMENTO","NO ES NECESARIO ES UN ELEMENTO OPCIONAL PARA LA SEGURIDAD","DEBO SOLAMENTE UTILIZAR LA CHAQUETA PROTECTORA","TOSAS LAS ANTERIORES"], ans:1, exp:"La respuesta correcta es: NO ES NECESARIO ES UN ELEMENTO OPCIONAL PARA LA SEGURIDAD."},
  // ── MECÁNICA
  {cat:"Mecánica", q:"QUE SIGNIFICA CUANDO A UN COSTADO DE LA LLANTA TIENE LA SIGUIENTE INFORMACIÓN 140/80-17", opts:["SON LAS CARACTERÍSTICAS DEL COLOR DE LA LLANTA","ME INDICA LA ALTURA, ANCHURA Y RIN DE LA LLANTA","ES LA FECHA DE VENCIMIENTO DE LA LLANTA","LA A Y B SON CORRECTAS"], ans:1, exp:"La respuesta correcta es: ME INDICA LA ALTURA, ANCHURA Y RIN DE LA LLANTA."},
  // ── CONDUCCIÓN SEGURA
  {cat:"Conducción Segura", q:"A CUANTA DISTANCIA DEBEN IR UBICADOS LOS CONOS AL MOMENTO DE COLOCARLOS ANTES DE UNA CURVA", opts:["20 METROS","30 METROS","40 METROS","50 METROS"], ans:3, exp:"La respuesta correcta es: 50 METROS."},
  // ── GENERAL
  {cat:"General", q:"EN QUE PARTE DEBEN IR UBICADOS LOS CONOS AL MOMENTO DE DETENER EL VEHÍCULO VARADO DE LA VÍA", opts:["SOLAMENTE ADELANTE","ADELANTE Y ATRÁS DEL VEHÍCULO","SOLAMENTE ATRÁS","EN TODOS LOS LADOS DEL VEHÍCULO"], ans:1, exp:"La respuesta correcta es: ADELANTE Y ATRÁS DEL VEHÍCULO."},
  {cat:"General", q:"CADA CUANTOS SEGUNDOS ES RECOMENDABLE ESTAR UTILIZANDO LOS ESPEJOS RETROVISORES PARA ESTAR ATENTO DE NUESTRO ENTORNO", opts:["10 SEGUNDOS","20 SEGUNDOS","50 SEGUNDOS","60 SEGUNDOS"], ans:0, exp:"La respuesta correcta es: 10 SEGUNDOS."},
  {cat:"General", q:"AL MOMENTO DE IR UN VEHÍCULO SUBIENDO UNA PENDIENDO Y EL OTRO BAJÁNDOLA Y LOS DOS TRATAN DE GIRAR HACIA EL MISMO LADO QUIEN TIENE PRELACIÓN", opts:["EL QUE VA SUBIENDO","EL QUE VA BAJANDO","EL QUE VA A GIRAR HACIA LA DERECHA","EL QUE VA A GIRAR A LA IZQUIERDA"], ans:0, exp:"La respuesta correcta es: EL QUE VA SUBIENDO."},
  // ── CONDUCCIÓN SEGURA
  {cat:"Conducción Segura", q:"A QUÉ VELOCIDAD YO DEBO REALIZAR EL ADELANTAMIENTO CON EL DIRECCIONAL IZQUIERDO EN UNA CURVA", opts:["30 KM","40 KM","50 KM","NINGUNA ES CIERTA"], ans:3, exp:"La respuesta correcta es: NINGUNA ES CIERTA."},
  // ── MOTOCICLISTAS
  {cat:"Motociclistas", q:"PORQUE LADO EL CONDUCTOR Y PASAJERO DE UNA MOTOCICLETA DEBEN SUBIRSE Y BAJARSE DE ESTE", opts:["POR EL LADO DERECHO","POR EL LADO IZQUIERDO","POR EL LADO DERECHO CON LA MOTO APAGADA","NINGUNA DE las anteriores"], ans:1, exp:"La respuesta correcta es: POR EL LADO IZQUIERDO."},
  // ── GENERAL
  {cat:"General", q:"EN QUE HORARIO DEBO HACER EL USO DEL CHALECO O PRENDA REFLECTIVA CUANDO ES DE USO OBLIGATORIO", opts:["DESDE LAS 7PM A 6AM","DESDE LAS 6PM A 6AM","DESDE LAS 6PM A 5AM","DESDE LAS 7PM A 5AM"], ans:1, exp:"La respuesta correcta es: DESDE LAS 6PM A 6AM."},
  // ── PRIMEROS AUXILIOS
  {cat:"Primeros Auxilios", q:"QUE SIGNIFICA LA PALABRA SOAT", opts:["SEGURO OBLIGATORIO DE ACELERACIÓN TÉCNICA","SEGURO OBLIGATORIO DE ACCIDENTES DE TRANSITO","SEGURO OBLIGATORIO DE AYUDA DE TRANSITO","SEGURO OBLIGATORIO DE ACCIDENTES DE TODO TIPO"], ans:1, exp:"La respuesta correcta es: SEGURO OBLIGATORIO DE ACCIDENTES DE TRANSITO."},
  // ── DOCUMENTOS
  {cat:"Documentos", q:"QUÉ DOCUMENTO AUTORIZA A UNA PERSONA PARA LA CONDUCCIÓN DE VEHÍCULOS CON VALIDEZ EN TODO EL TERRITORIO NACIONAL", opts:["LICENCIA DE TRANSITO","SOAT","LICENCIA DE CONDUCCIÓN","PASE DE CONDUCCIÓN"], ans:2, exp:"La respuesta correcta es: LICENCIA DE CONDUCCIÓN."},
  // ── GENERAL
  {cat:"General", q:"DE QUÉ COLOR DEBEN SER LOS DIRECCIONALES DE UN VEHÍCULO", opts:["BLANCO","AMARILLO","ROJO","AZUL"], ans:1, exp:"La respuesta correcta es: AMARILLO."},
  // ── MECÁNICA
  {cat:"Mecánica", q:"QUE HACE PARTE DE UNA REVISIÓN PREOPERACIONAL DE UN VEHÍCULO", opts:["REVISARLE EL ESTADO DE LAS LLANTAS","REVISARLE EL ESTADO DE LOS LÍQUIDOS","REVISAR LA DOCUMENTACIÓN DEL VEHÍCULO","TODAS LAS ANTERIORES"], ans:3, exp:"La respuesta correcta es: TODAS LAS ANTERIORES."},
  // ── SEÑALES
  {cat:"Señales", q:"DE LAS SIGUIENTES SEÑALES DE TRANSITO CUAL TIENE MAYOR PRELACION SEGÚN ART.111", opts:["SEÑALES VERTICALES","SEÑALES HORIZONTALES","SEÑALES LUMINOSAS","SEÑALES CORPORALES"], ans:3, exp:"La respuesta correcta es: SEÑALES CORPORALES."},
  // ── PEATONES Y CICLISTAS
  {cat:"Peatones y Ciclistas", q:"CUÁLES SON LOS TIPOS DE SEMÁFOROS QUE EXISTEN EN LA VÍA", opts:["SEMÁFORO DE VEHÍCULOS PEQUEÑOS Y GRANDES","SEMÁFORO VEHICULAR, PEATONAL Y DIRECCIONAL","SEMÁFORO VEHICULAR Y PEATONAL","SEMÁFORO VEHICULAR"], ans:1, exp:"La respuesta correcta es: SEMÁFORO VEHICULAR, PEATONAL Y DIRECCIONAL."},
  // ── SEÑALES
  {cat:"Señales", q:"LOS CIUDADANOS EL DÍA DE HOY EN SU GRAN MAYORÍA DESCONOCEN O DESOBEDECEN LAS SEÑALES DE TRANSITO", opts:["LAS DESOBEDECEN","LAS DESCONOCEN","NINGUNA DE las anteriores","TODAS LAS ANTERIORES"], ans:0, exp:"La respuesta correcta es: LAS DESOBEDECEN."},
  // ── MOTOCICLISTAS
  {cat:"Motociclistas", q:"CUÁL ES LA PARTE MÁS IMPORTANTE EN UNA MOTOCICLETA", opts:["EL CHASIS","LA DIRECCIÓN","LA BATERÍA","EL MOTOR"], ans:3, exp:"La respuesta correcta es: EL MOTOR."},
  // ── MECÁNICA
  {cat:"Mecánica", q:"EN QUÉ LADO SE ENCUENTRA UBICADO EL PEDAL DEL FRENO EN EL CARRO", opts:["IZQUIERDO","CENTRO","DERECHO","NINGUNO"], ans:1, exp:"La respuesta correcta es: CENTRO."},
  // ── GENERAL
  {cat:"General", q:"CUÁLES SON LOS DOS TIPOS DE VEHÍCULOS QUE EXISTEN", opts:["MANUALES Y AUTOMÁTICOS","AUTOMÁTICOS Y DIRECCIONALES","DE GASOLINA Y AUTOMÁTICOS","TODOS LOS ANTERIORES"], ans:0, exp:"La respuesta correcta es: MANUALES Y AUTOMÁTICOS."},
  {cat:"General", q:"CUANTAS VECES DEBO HACER USO DEL DIRECCIONAL AL MOMENTO DE HACER UN ADELANTAMIENTO DE OTRO VEHÍCULO", opts:["SOLO 1, EL IZQUIERDO","2, EL IZQUIERDO Y EL DERECHO","NINGUNO DE ESTOS","SOLAMENTE EL DERECHO"], ans:1, exp:"La respuesta correcta es: 2, EL IZQUIERDO Y EL DERECHO."},
  // ── MECÁNICA
  {cat:"Mecánica", q:"EN UN VEHÍCULO(CARRO) MANUAL CUAL ES EL COMANDO INFERIOR QUE DA EL MOVIMIENTO", opts:["ACELERADOR","FRENO","EMBRAGUE","CAMBIOS"], ans:2, exp:"La respuesta correcta es: EMBRAGUE."},
  // ── GENERAL
  {cat:"General", q:"CUÁL ES LA FUNCIÓN DEL ACELERADOR EN UN VEHÍCULO", opts:["DARLE FUERZA AL VEHÍCULO","DARLE MOVIMIENTO AL VEHÍCULO","DARLE MOVIMIENTO Y FUERZA AL VEHÍCULO","NINGUNA DE las anteriores"], ans:0, exp:"La respuesta correcta es: DARLE FUERZA AL VEHÍCULO."},
  // ── CONDUCCIÓN SEGURA
  {cat:"Conducción Segura", q:"QUE SUCEDE CON LA DIRECCIÓN DE UN VEHÍCULO A MAYOR VELOCIDAD", opts:["SU DIRECCIÓN SE VUELVE MÁS SENSIBLE","SU DIRECCIÓN SE VUELVE MÁS RÍGIDA","TIENE MAYOR CONTROL DEL VEHÍCULO","TODAS LAS ANTERIORES"], ans:0, exp:"La respuesta correcta es: SU DIRECCIÓN SE VUELVE MÁS SENSIBLE."},
  // ── PRIMEROS AUXILIOS
  {cat:"Primeros Auxilios", q:"QUE MANIOBRA PUEDO REALIZAR AL MOMENTO DE MOVILIZARME EN UN VEHÍCULO A 100 KM/H Y QUEDARME SIN FRENOS PRINCIPALES", opts:["ESTRELLAR EL VEHÍCULO CONTRA UN OBSTÁCULO PARA MINIMIZAR LOS RIESGOS","SELECCIONAR REVERSA EN EL VEHÍCULO","SUJETAR RÍGIDAMENTE EL MANUBRIO Y BAJAR LOS CAMBIOS MODERADAMENTE","TIRARME DEL VEHÍCULO EN MARCHA PARA MINIMIZAR LAS POSIBLES LESIONES"], ans:2, exp:"La respuesta correcta es: SUJETAR RÍGIDAMENTE EL MANUBRIO Y BAJAR LOS CAMBIOS MODERADAMENTE."},
  // ── MOTOCICLISTAS
  {cat:"Motociclistas", q:"EN QUE UBICACIÓN DEBEN IR LOS ESPEJOS RETROVISORES EN UNA MOTOCICLETA", opts:["EN LA PARTE DE ARRIBA DEL MANUBRIO CON VISIBILIDAD HACIA ATRÁS","EN LA PARTE DE LA MANIGUETA CON VISIBILIDAD HACIA ATRÁS","EN CUALQUIER UBICACIÓN CON VISIBILIDAD HACIA ATRÁS","EN LA PARTE CENTRO DEL MANUBRIO SIN IMPORTAR QUE TENGA VISIBILIDAD HACIA ATRÁS"], ans:0, exp:"La respuesta correcta es: EN LA PARTE DE ARRIBA DEL MANUBRIO CON VISIBILIDAD HACIA ATRÁS."},
  // ── GENERAL
  {cat:"General", q:"CUANTOS ESPEJOS TIENE UN CARRO", opts:["1","2","3","4"], ans:2, exp:"La respuesta correcta es: 3."},
  // ── MECÁNICA
  {cat:"Mecánica", q:"CUANTOS FRENOS TIENE UN CARRO", opts:["2","3","4","5"], ans:1, exp:"La respuesta correcta es: 3."},
  {cat:"Mecánica", q:"CUÁL ES EL FRENO PRINCIPAL DE UN CARRO", opts:["FRENO DE PIE","FRENO DE MANO","FRENO DE MOTOR","NINGUNO DE ESTOS"], ans:0, exp:"La respuesta correcta es: FRENO DE PIE."},
  {cat:"Mecánica", q:"CUANTOS LÍQUIDOS PUEDE TRAER UN VEHÍCULO (CARRO) EN LA PARTE DEL MOTOR", opts:["TODOS LOS CARROS TRAEN 4 LÍQUIDOS","TODOS LOS CARROS TRAEN 5 LÍQUIDOS","EN ALGUNOS CASOS TRAEN 4 Y EN OTROS 5","TODOS LOS CARROS TRAEN 6 LÍQUIDOS CON LA GASOLINA"], ans:2, exp:"La respuesta correcta es: EN ALGUNOS CASOS TRAEN 4 Y EN OTROS 5."},
  // ── GENERAL
  {cat:"General", q:"EN QUE PARTE SE ENCUENTRA LA TRACCIÓN DE LA MAYORÍA DE LOS VEHÍCULOS PEQUEÑOS TIPO PERSONALES", opts:["EN LAS RUEDAS DELANTERAS","EN LAS RUEDAS TRASERAS","EN TODAS LAS RUEDAS","TODAS LAS ANTERIORES"], ans:0, exp:"La respuesta correcta es: EN LAS RUEDAS DELANTERAS."},
  // ── INFRACCIONES
  {cat:"Infracciones", q:"CUANTO ES EL VALOR DEL COMPARENDO POR NO PORTAR ELEMENTOS DEL KIT DE CARRETERA DE UN VEHÍCULO", opts:["8 SMDLV","15 SMDLV","30 SMDLV","45 SMDLV"], ans:1, exp:"La respuesta correcta es: 15 SMDLV."},
  // ── AUTORIDADES Y NORMAS
  {cat:"Autoridades y Normas", q:"EN QUE SITUACIÓN DEBO UTILIZAR EL CINTURÓN DE SEGURIDAD EN UN VEHÍCULO", opts:["SOLAMENTE EN EL PERÍMETRO RURAL","SOLAMENTE EN EL PERÍMETRO URBANO","EN TODO MOMENTO QUE EL VEHÍCULO SE ENCUENTRE EN MOVIMIENTO","CUANDO SE ENCUENTREN AUTORIDADES DE TRÁNSITO EN LA VÍA"], ans:2, exp:"La respuesta correcta es: EN TODO MOMENTO QUE EL VEHÍCULO SE ENCUENTRE EN MOVIMIENTO."},
  // ── MOTOCICLISTAS
  {cat:"Motociclistas", q:"EN QUÉ MOMENTO DEBO UTILIZAR CASCO DE SEGURIDAD EN UN CARRO", opts:["SOLAMENTE EN EL PERÍMETRO RURAL","SOLAMENTE EN EL PERÍMETRO URBANO","EN TODO MOMENTO QUE EL VEHÍCULO SE ENCUENTRE EN MOVIMIENTO","NINGUNA DE anteriores"], ans:3, exp:"La respuesta correcta es: NINGUNA DE anteriores."},
  // ── CONDUCCIÓN SEGURA
  {cat:"Conducción Segura", q:"QUÉ CONSECUENCIAS PUEDE TENER AL CONDUCIR UN VEHÍCULO A ALTAS VELOCIDADES", opts:["AUMENTO DE SU CAPACIDAD DE REACCIÓN","DISMINUCIÓN DE SU CAPACIDAD DE REACCIÓN","AUMENTO DE SU CAPACIDAD VISUAL","AUMENTO DE SU CAPACIDAD PARA JUZGAR LA VELOCIDAD"], ans:1, exp:"La respuesta correcta es: DISMINUCIÓN DE SU CAPACIDAD DE REACCIÓN."},
  // ── GENERAL
  {cat:"General", q:"EL ELEMENTO MÁS IMPORTANTE PARA LA SEGURIDAD PASIVA ES", opts:["CINTURÓN DE SEGURIDAD","BOLSAS DE AIRE","APOYACABEZAS","SISTEMA DE RETENCIÓN INFANTIL"], ans:0, exp:"La respuesta correcta es: CINTURÓN DE SEGURIDAD."},
  // ── MECÁNICA
  {cat:"Mecánica", q:"QUE ELEMENTO NO HACE PARTE DEL SISTEMA DE SEGURIDAD ACTIVA", opts:["FRENOS","LLANTAS","BOLSA DE AIRE","A Y B SON CORRECTAS"], ans:2, exp:"La respuesta correcta es: BOLSA DE AIRE."},
  // ── CONDUCCIÓN SEGURA
  {cat:"Conducción Segura", q:"LOS CAMBIOS EN LA CAJA DE VELOCIDADES DEL AUTOMOTOR ESTÁN DIVIDIDOS EN", opts:["CONTRA MARCHA Y VELOCIDAD","VELOCIDAD, IMPULSO Y ACELERACIÓN","FUERZA Y VELOCIDAD","NINGUNA DE LAS ANTERIORES"], ans:2, exp:"La respuesta correcta es: FUERZA Y VELOCIDAD."},
  // ── MOTOCICLISTAS
  {cat:"Motociclistas", q:"CUAL TIPO DE CASCO ES MÁS RECOMENDADO AL MOMENTO DE CONDUCIR UNA MOTOCICLETA", opts:["CASCO ABIERTO CERTIFICADO","CASCO ABATIBLE CERTIFICADO","CASCO CERRADO CERTIFICADO","NINGUNA DE LAS ANTERIORES"], ans:2, exp:"La respuesta correcta es: CASCO CERRADO CERTIFICADO."},
  {cat:"Motociclistas", q:"EL SIGUIENTE CASCO EN QUE PERÍMETRO ES PERMITIDO SU USO", opts:["SOLAMENTE EN EL PERIMETRO URBANO","SOLAMENTE EN EL PERIMETRO RURAL","EN CUALQUIER PERIMETRO YA QUE ES UN CASCO CERTIFICADO","EN NINGUN PERIMETRO YA QUE NO CUMPLE CON LOS REQUISITOS PARA SER LEGAL SU USO"], ans:0, exp:"La respuesta correcta es: SOLAMENTE EN EL PERIMETRO URBANO.", img:"./imgs/preguntas/q176_casco.png"},
  {cat:"Motociclistas", q:"AL MOMENTO DE CONDUCIR UNA MOTOCICLETA YO DEBO:", opts:["UTILIZAR EL CASCO DE CONDUCCIÓN","UTILIZAR EL CHALECO FLECTIVO SI ES DE USO OBLIGATORIO","REALIZAR LA REVISIÓN PREOPEACIONAL DEL VEHÍCULO","TODAS LAS ANTERIORES"], ans:3, exp:"La respuesta correcta es: TODAS LAS ANTERIORES."},
  // ── GENERAL
  {cat:"General", q:"AL MOMENTO DE CONDUCIR UN VEHÍCULO (CARRO) YO DEBO:", opts:["REALIZAR LA PREOPERACIONAL DEL VEHÍCULO","TENER EL VEHÍCULO EN BUENAS CONDICIONES","LLEVAR LA DOCUMENTACIÓN AL DÍA","TODAS LAS ANTERIORES"], ans:3, exp:"La respuesta correcta es: TODAS LAS ANTERIORES."},
  // ── MECÁNICA
  {cat:"Mecánica", q:"CUÁLES SON LOS TIPOS DE ALIMENTACIÓN QUE PUEDE TRAER UN VEHÍCULO", opts:["GASOLINA, GAS, ACPM Y MANIVELA","LÍQUIDO REFRIGERANTE, GASOLINA Y GAS","ACPM, GAS Y GASOLINA","NINGUNA DE LAS ANTERIORES"], ans:2, exp:"La respuesta correcta es: ACPM, GAS Y GASOLINA."},
  // ── PRIMEROS AUXILIOS
  {cat:"Primeros Auxilios", q:"QUE SIGNIFICA LAS SIGLAS CEA EN LA CONDUCCIÓN", opts:["CENTRO DE ENSEÑANZA DE ACCIDENTES","CENTRO DE ENSEÑANZA AUTOMOVILÍSTICA","CENTRO DE EDUCACIÓN DE AUTOS","CENTRO DE EDUCACIÓN DE ACTORES VIALES"], ans:1, exp:"La respuesta correcta es: CENTRO DE ENSEÑANZA AUTOMOVILÍSTICA."},
  // ── MOTOCICLISTAS
  {cat:"Motociclistas", q:"DE QUÉ COLOR DEBEN SER LOS CASCOS AL MOMENTO DE CONDUCIR UNA MOTOCICLETA EN LAS VÍAS RURALES", opts:["DE COLORES CLAROS PARA SU VISIBILIDAD","DE COLORES OSCUROS PARA QUE LA LUZ NO REBOTE HACIA LOS DEMÁS CONDUCTORES","DE CUALQUIER COLOR, LO IMPORTANTE ES QUE SEAN CERTIFICADOS Y SU BUEN USO","LA A Y B SON CORRECTAS"], ans:2, exp:"La respuesta correcta es: DE CUALQUIER COLOR, LO IMPORTANTE ES QUE SEAN CERTIFICADOS Y SU BUEN USO."},
  // ── INFRACCIONES
  {cat:"Infracciones", q:"CUANTO ES EL VALOR DEL COMPARENDO POR ESTACIONARSE EN UN SITIO DE ESTACIONAMIENTO PREFERENCIAL", opts:["8 SMDLV","15 SMDLV","30 SMDLV","45 SMDLV"], ans:1, exp:"La respuesta correcta es: 15 SMDLV."},
  // ── GENERAL
  {cat:"General", q:"UN MENOR DE EDAD DESDE CUANTOS AÑOS PUEDE OCUPAR EL PUESTO DE COPILOTO EN EL VEHÍCULO(CARRO)", opts:["DESDE LOS 10 AÑOS","DESDE LOS 12 AÑOS","DESDE LOS 15 AÑOS","DESDE LOS 17 AÑOS"], ans:0, exp:"La respuesta correcta es: DESDE LOS 10 AÑOS."},
  // ── PRIMEROS AUXILIOS
  {cat:"Primeros Auxilios", q:"CADA CUANTO TIEMPO MUEREN PERSONAS A NIVEL MUNDIAL POR ACCIDENTES DE TRANSITO", opts:["CADA 10 MINUTOS","CADA 1 MINUTO","CADA 45 SEGUNDOS","CADA 23 SEGUNDOS"], ans:3, exp:"La respuesta correcta es: CADA 23 SEGUNDOS."},
  // ── GENERAL
  {cat:"General", q:"EN QUÉ SITUACIÓN PODEMOS HACER USO DE LAS LUCES ALTAS DE NUESTRO VEHÍCULO", opts:["EN EL PERÍMETRO RURAL","SIEMPRE Y CUANDO NINGÚN VEHÍCULO TRÁNSITO EN SENTIDO CONTRARIO A NUESTRO VEHÍCULO","CUANDO LA VISIBILIDAD DE LA VÍA SEA POCA POR FALTA DE ILUMINACIÓN","TODAS LAS ANTERIORES"], ans:3, exp:"La respuesta correcta es: TODAS LAS ANTERIORES."},
  // ── SEÑALES
  {cat:"Señales", q:"EN QUE SITUACIONES ESTÁ PERMITIDO CRUZAR UN SEMÁFORO EN ROJO", opts:["EN NINGUNA SITUACIÓN, CRUZARSE UN SEMÁFORO EN ROJO ESTÁ PROHIBIDO","CUANDO VALLA A REALIZAR UN GIRO A LA DERECHA CON LAS DEBIDAS PRECAUCIONES","CUANTO UN VEHÍCULO DE EMERGENCIA NECESITA QUE LE DEN VIA","LA B Y C SON CORRECTAS"], ans:3, exp:"La respuesta correcta es: LA B Y C SON CORRECTAS."},
  // ── MOTOCICLISTAS
  {cat:"Motociclistas", q:"QUE FRENO ES MÁS SEGURO EN UNA MOTOCICLETA", opts:["EL FRENO DE TAMBOR O DE BANDAS","EL FRENO DE DISCO","EL FRENO ABS","NINGUNO DE ESTOS"], ans:2, exp:"La respuesta correcta es: EL FRENO ABS."},
  // ── GENERAL
  {cat:"General", q:"DE QUÉ ORIGEN EN LA CERTIFICACIÓN DE CASCOS DOT", opts:["ES EUROPEA","ES ESTADOUNIDENSE","ES COLOMBIANA","ES CHILENA"], ans:1, exp:"La respuesta correcta es: ES ESTADOUNIDENSE."},
  // ── SEÑALES
  {cat:"Señales", q:"COMO SE LLAMA LA SIGUIENTE SEÑAL DE TRANSITO SEGÚN EL CÓDIGO NACIONAL DE TRANSITO", opts:["PELIGRO CON ANIMALES","ANIMALES EN LA VÍA","ANIMALES EN LA CARRETERA","VACAS EN LA VÍA"], ans:1, exp:"La respuesta correcta es: ANIMALES EN LA VÍA.", img:"./imgs/preguntas/q189_animales.png"},
  {cat:"Señales", q:"QUE NOS INDICAN LAS SEÑALES INFORMATIVAS", opts:["NOS INFORMAN DE UBICACIÓN","NOS INFORMAN DE OBJETOS","NOS INFORMAN DE PELIGROS","NOS INFORMAN DE PREVENCIONES"], ans:0, exp:"La respuesta correcta es: NOS INFORMAN DE UBICACIÓN."},
  {cat:"Señales", q:"A QUE NOS HACE REFERENCIA LA SIGUIENTE SEÑAL DE TRANSITO", opts:["ZONA DE DESCANSO","HOSPEDAJE","HOTEL","TODAS LAS ANTERIORES"], ans:3, exp:"La respuesta correcta es: TODAS LAS ANTERIORES.", img:"./imgs/preguntas/q191_hospedaje.png"},
  {cat:"Señales", q:"COMO SE LLAMA LA SIGUIENTE SEÑAL DE TRANSITO SEGÚN EL CÓDIGO NACIONAL DE TRANSITO", opts:["RESALTO","REDUCTOR DE VELOCIDAD","POLICÍA ACOSTADO","TODAS LAS ANTERIORES"], ans:0, exp:"La respuesta correcta es: RESALTO.", img:"./imgs/preguntas/q192_resalto.png"},
  // ── GENERAL
  {cat:"General", q:"CUANTOS DIRECCIONALES TIENE UN VEHICULÓ", opts:["1 DIRECCIONAL QUE SE ACCIONA AL PARQUEAR","2 DIRECCIONALES, EL DE LA DERECHA Y LA IZQUIERDA","3 DIRECCIONALES, CON LOS DE PARQUEO","4 DIRECCIONALES, DOS EN LA PARTE DE ADELANTE Y DOS ATRÁS"], ans:3, exp:"La respuesta correcta es: 4 DIRECCIONALES, DOS EN LA PARTE DE ADELANTE Y DOS ATRÁS."},
  {cat:"General", q:"CARACTERÍSTICAS DE LOS MOTORES DE 2T", opts:["QUE LOS MOTORES DE 2T SIEMPRE BOTAN HUMO PORQUE LLEVAN MEZCLA EN LA GASOLINA","QUE EL PROCESO DE COMBUSTIÓN LO HACEN MÁS CORTO QUE LOS MOTORES DE 4T","LOS MOTORES DE 2T TIENEN MÁS POTENCIA QUE LOS DE 4T","TODAS LAS ANTERIORES"], ans:3, exp:"La respuesta correcta es: TODAS LAS ANTERIORES."},
  {cat:"General", q:"COMO DEBE SER EL DESCENSO DE LOS OCUPANTES DE UN VEHÍCULO(CARRO)", opts:["LOS PASAJEROS DEBEN BAJARSE POR EL LADO DE LA ACERA Y EL CONDUCTOR SOLAMENTE POR LA IZQUIERDA","TODOS LOS OCUPANTES DEBEN BAJARSE POR EL LADO DERECHO DEL VEHÍCULO","TODOS LOS OCUPANTES DEBEN BAJARSE POR EL LADO IZQUIERDO DEL VEHÍCULO","NINGUNA DE LAS ANTERIORES"], ans:0, exp:"La respuesta correcta es: LOS PASAJEROS DEBEN BAJARSE POR EL LADO DE LA ACERA Y EL CONDUCTOR SOLAMENTE POR LA IZQUIERDA."},
  {cat:"General", q:"QUE ELEMENTO NO ES OBLIGATORIO EN EL KIT DE CARRETERA DE UN VEHÍCULO", opts:["EXTINTOR","CRUCETA","TACOS","CHALECO"], ans:3, exp:"La respuesta correcta es: CHALECO."},
  // ── MOTOCICLISTAS
  {cat:"Motociclistas", q:"CUAL AFIRMACIÓN ES FALSA", opts:["EL ADELANTAMIENTO SE DEBE REALIZAR POR EL LADO IZQUIERDO","LA LICENCIA TIPO A2 ES PARA MOTOCICLETAS MAYORES DE 125CC","LA VELOCIDAD MÁXIMA PERMITIDA EN COLOMBIA PARA VEHÍCULOS PARTICULARES ES DE 120KM","LA VELOCIDAD MÁXIMA EN COLOMBIA PARA CUALQUIER VEHÍCULO ES 80KM"], ans:3, exp:"La respuesta correcta es: LA VELOCIDAD MÁXIMA EN COLOMBIA PARA CUALQUIER VEHÍCULO ES 80KM."},
  // ── GENERAL
  {cat:"General", q:"DE QUÉ COLOR DEBEN SER LAS PLACAS DE  LOS VEHÍCULOS DE SERVICIO PUBLICO", opts:["DE COLOR AMARILLO CON PLACAS BLANCA","DE COLOR BLANCO CON PLACAS BLANCA","CUALQUIER COLOR, LO IMPORTANTE ES QUE TENGA PLACAS BLANCAS","LA A Y B SON CORRECTAS"], ans:2, exp:"La respuesta correcta es: CUALQUIER COLOR, LO IMPORTANTE ES QUE TENGA PLACAS BLANCAS."},
  // ── MOTOCICLISTAS
  {cat:"Motociclistas", q:"LOS VEHÍCULOS TIPO MOTOCICLETA DEBEN LLEVAR OBLIGATORIAMENTE UN KIT DE CARRETERA", opts:["SI, LA LEY LOS EXIGE ACTUALMENTE","NO, ES DE USO RECOMENDABLE MAS NO OBLIGATORIO","SI, SEGÚN EL CÓDIGO NACIONAL DE TRÁNSITO LEY 769 DEL 2002","NINGUNA DE las anteriores"], ans:1, exp:"La respuesta correcta es: NO, ES DE USO RECOMENDABLE MAS NO OBLIGATORIO."},
  // ── MECÁNICA
  {cat:"Mecánica", q:"PORQUE ES IMPORTANTE CAMBIAR EL ACEITE DE UN VEHÍCULO", opts:["PARA QUE LA VIDA DEL MOTOR SEA MÁS LARGA","PARA QUE EL MOTOR TENGA LUBRICACIÓN","PARA EVITAR DAÑOS EN EL MOTOR","TODAS LAS ANTERIORES"], ans:3, exp:"La respuesta correcta es: TODAS LAS ANTERIORES."},
];
