
/* ══════════════════════════════════════════════════════════════
   BANCO DE PREGUNTAS — 100 preguntas de tránsito Colombia
══════════════════════════════════════════════════════════════ */
const PREGUNTAS = [
  // ── SEÑALES DE TRÁNSITO
  {cat:"Señales", q:"¿Qué indica una señal de PARE (octagonal roja)?", opts:["Reducir la velocidad","Detenerse completamente antes de la línea de pare","Ceder el paso solo si hay vehículos","Continuar con precaución"], ans:1, exp:"La señal PARE obliga al conductor a detenerse totalmente antes de la línea de detención o del cruce peatonal."},
  {cat:"Señales", q:"¿Qué significa una señal circular con borde rojo y número 60?", opts:["Velocidad mínima permitida","Velocidad máxima permitida","Distancia en metros","Zona escolar a 60 metros"], ans:1, exp:"Las señales circulares con borde rojo y número indican velocidad máxima permitida en ese tramo."},
  {cat:"Señales", q:"¿Qué indica una señal triangular con borde rojo y vértice hacia abajo?", opts:["Peligro adelante","Ceda el paso","Zona escolar","Curva peligrosa"], ans:1, exp:"El triángulo invertido con borde rojo es la señal de CEDA EL PASO, que obliga a dar preferencia a otros vehículos."},
  {cat:"Señales", q:"¿Qué color tienen las señales informativas en Colombia?", opts:["Rojo","Amarillo","Verde o azul","Naranja"], ans:2, exp:"Las señales informativas son verdes (para rutas) o azules (para servicios y zonas urbanas)."},
  {cat:"Señales", q:"¿Qué indica una señal amarilla en forma de diamante?", opts:["Prohibición","Obligación","Prevención o advertencia","Información"], ans:2, exp:"Las señales amarillas en rombo (diamante) son preventivas, advierten sobre condiciones peligrosas adelante."},
  {cat:"Señales", q:"¿Qué significa una X en la carretera antes de un cruce de ferrocarril?", opts:["Zona de parqueo","Cruce de peatones","Cruce de línea férrea sin barrera","Fin de vía"], ans:2, exp:"La X pintada en la vía indica aproximación a un cruce ferroviario, advirtiendo al conductor que debe reducir velocidad."},
  {cat:"Señales", q:"¿Qué indica una señal de flecha amarilla parpadeante en semáforo?", opts:["Avanzar sin detenerse","Giro permitido con precaución cediendo el paso a peatones","Giro prohibido","Esperar luz verde"], ans:1, exp:"La flecha amarilla parpadeante permite el giro pero el conductor debe ceder el paso a peatones y ciclistas."},
  {cat:"Señales", q:"¿Qué señal indica que está prohibido adelantar?", opts:["Línea blanca discontinua al centro","Línea amarilla continua al centro","Línea azul lateral","Doble línea blanca"], ans:1, exp:"La línea amarilla continua al centro de la calzada prohíbe adelantar o invadir el carril contrario."},
  {cat:"Señales", q:"¿Qué significa la luz roja del semáforo?", opts:["Reducir velocidad","Continuar con precaución","Detenerse obligatoriamente","Ceder el paso"], ans:2, exp:"La luz roja obliga a detenerse completamente antes de la línea de pare o la intersección."},
  {cat:"Señales", q:"¿Qué indica la luz verde del semáforo?", opts:["Avanzar si no hay obstáculos","Girar siempre a la derecha","Acelerar al máximo","Detenerse"], ans:0, exp:"La luz verde indica que puede avanzar, pero siempre verificando que la vía esté libre y cediendo el paso donde corresponda."},
  // ── NORMAS DE TRÁNSITO
  {cat:"Normas", q:"¿Cuál es la velocidad máxima permitida en zonas residenciales urbanas en Colombia?", opts:["30 km/h","40 km/h","50 km/h","60 km/h"], ans:0, exp:"Según el Código Nacional de Tránsito, en zonas residenciales la velocidad máxima es 30 km/h."},
  {cat:"Normas", q:"¿Cuál es la velocidad máxima en carretera (vía primaria) de dos carriles?", opts:["80 km/h","100 km/h","120 km/h","60 km/h"], ans:1, exp:"En carreteras primarias de dos carriles bidireccionales la velocidad máxima es 100 km/h para automóviles."},
  {cat:"Normas", q:"¿A qué distancia mínima se debe encender las luces altas en la noche?", opts:["50 metros","100 metros","150 metros","200 metros"], ans:1, exp:"Las luces altas deben encenderse cuando no haya visibilidad suficiente a 100 metros de distancia."},
  {cat:"Normas", q:"¿Cuándo se debe usar la bocina del vehículo?", opts:["Para saludar a conocidos","En zonas escolares para alertar","Solo en casos necesarios de seguridad vial","Siempre que se adelante un vehículo"], ans:2, exp:"La bocina solo debe usarse para prevenir accidentes. Su uso innecesario está prohibido especialmente en zonas hospitalarias y residenciales."},
  {cat:"Normas", q:"¿Qué debe hacer el conductor al llegar a un cruce sin señalización?", opts:["Quien llega primero tiene prioridad","Ceder el paso al vehículo de la derecha","Ceder el paso al vehículo de la izquierda","El vehículo más grande tiene prioridad"], ans:1, exp:"En intersecciones sin señalización, se debe ceder el paso al vehículo que viene por la derecha."},
  {cat:"Normas", q:"¿Con qué BAC (gramos de alcohol por litro de sangre) se considera conducción en estado de embriaguez en Colombia?", opts:["Más de 0.2 g/L","Más de 0.4 g/L","Más de 0.8 g/L","Más de 1.0 g/L"], ans:1, exp:"Según la Ley 1696 de 2013, conducir con 0.4 g/L o más en sangre es conducción en estado de embriaguez."},
  {cat:"Normas", q:"¿Cuándo es obligatorio el uso del cinturón de seguridad?", opts:["Solo en carretera","Solo el conductor","Todos los ocupantes siempre","Solo en viajes largos"], ans:2, exp:"El cinturón de seguridad es obligatorio para todos los ocupantes del vehículo en todo momento."},
  {cat:"Normas", q:"¿Qué se debe hacer al acercarse a un vehículo de emergencia con sirena activa?", opts:["Acelerar para despejar la vía","Orillarse a la derecha y detenerse","Continuar normalmente","Activar las luces de emergencia y acelerar"], ans:1, exp:"Ante vehículos de emergencia con sirena y luces, el conductor debe orillarse a la derecha y detenerse."},
  {cat:"Normas", q:"¿Cuántos metros mínimos antes de girar se deben encender las direccionales?", opts:["10 metros","20 metros","30 metros","50 metros"], ans:2, exp:"Las señales de giro (direccionales) deben activarse al menos 30 metros antes de efectuar la maniobra."},
  {cat:"Normas", q:"¿Qué distancia mínima debe mantener con el vehículo de adelante?", opts:["La que permite detenerse de forma segura","2 metros","5 metros","10 metros"], ans:0, exp:"La distancia de seguimiento debe permitir detenerse de forma segura. Se recomienda la regla de los 3 segundos."},
  // ── LICENCIAS
  {cat:"Licencias", q:"¿Qué categoría de licencia se requiere para conducir una motocicleta de más de 125cc?", opts:["A1","A2","B1","C1"], ans:1, exp:"La categoría A2 habilita para conducir motocicletas de más de 125cc. La A1 es para motos de hasta 125cc."},
  {cat:"Licencias", q:"¿Qué categoría de licencia necesita un conductor de bus intermunicipal?", opts:["B1","B2","C1","C2"], ans:2, exp:"La categoría C1 habilita para conducir vehículos de transporte público de pasajeros y de carga liviana."},
  {cat:"Licencias", q:"¿Qué edad mínima se requiere para obtener licencia B1 (particular) en Colombia?", opts:["15 años","16 años","18 años","21 años"], ans:1, exp:"Para obtener la licencia de conducción categoría B1 se requiere mínimo 16 años en Colombia."},
  {cat:"Licencias", q:"¿Cada cuántos años se debe renovar la licencia de conducción en Colombia?", opts:["3 años","5 años","10 años","No se renueva"], ans:2, exp:"Según la normativa, la licencia de conducción debe renovarse cada 10 años para la mayoría de categorías."},
  {cat:"Licencias", q:"¿Qué documento expide el CEA al aprobar el curso de conducción?", opts:["La licencia de conducción definitiva","El certificado de aptitud","El SOAT","La tarjeta de propiedad"], ans:1, exp:"El CEA expide el Certificado de Aptitud en Conducción que habilita al estudiante para tramitar su licencia ante el organismo de tránsito."},
  // ── MECÁNICA BÁSICA
  {cat:"Mecánica", q:"¿Qué indica la luz del aceite encendida en el tablero?", opts:["Cambiar el aceite próximamente","Presión de aceite baja o sin aceite — detenerse inmediatamente","Aceite de motor caliente","Revisar el filtro de aire"], ans:1, exp:"La luz de aceite indica presión insuficiente. Continuar conduciendo puede destruir el motor; debe detenerse de inmediato."},
  {cat:"Mecánica", q:"¿Con qué frecuencia aproximada se debe revisar la presión de los neumáticos?", opts:["Una vez al año","Cada 6 meses","Mensualmente o antes de viajes largos","Cada 5 años"], ans:2, exp:"Se recomienda revisar la presión de los neumáticos mensualmente y antes de cada viaje largo."},
  {cat:"Mecánica", q:"¿Qué función tiene el líquido refrigerante del motor?", opts:["Lubricar las piezas del motor","Regular la temperatura del motor evitando el sobrecalentamiento","Limpiar el sistema de frenos","Transmitir la potencia"], ans:1, exp:"El refrigerante mantiene la temperatura del motor dentro del rango óptimo, evitando sobrecalentamiento o congelamiento."},
  {cat:"Mecánica", q:"¿Qué hacer si los frenos del vehículo fallan durante la marcha?", opts:["Apagar el motor inmediatamente","Reducir marchas, usar el freno de mano progresivamente y buscar una salida segura","Abrir la puerta para frenar","Acelerar para ganar control"], ans:1, exp:"En falla de frenos: reducir marchas, aplicar freno de mano progresivamente, buscar zona de escape (subida o arena) y avisar con bocina."},
  {cat:"Mecánica", q:"¿Cuál es la profundidad mínima legal del dibujo del neumático en Colombia?", opts:["0.8 mm","1.6 mm","2.0 mm","3.2 mm"], ans:1, exp:"La profundidad mínima legal del dibujo del neumático es 1.6 mm. Menos de esto representa peligro por pérdida de adherencia."},
  // ── PRIMEROS AUXILIOS
  {cat:"Primeros Auxilios", q:"Al llegar a un accidente de tránsito, ¿cuál es el primer paso?", opts:["Mover a los heridos de la vía","Asegurar la escena y llamar a emergencias (123)","Dar agua a los heridos","Tomar fotos del accidente"], ans:1, exp:"Lo primero es asegurar la escena (señalizar) y activar el sistema de emergencias llamando al 123 para atención especializada."},
  {cat:"Primeros Auxilios", q:"¿Cuándo NO se debe mover a un accidentado?", opts:["Cuando hay riesgo de incendio","Cuando está inconsciente","Siempre que haya trauma en columna o cabeza, a menos que haya peligro inminente","Cuando ya recibió primeros auxilios"], ans:2, exp:"No se debe mover a un accidentado con sospecha de trauma en columna o cabeza, salvo riesgo vital como incendio o ahogamiento."},
  {cat:"Primeros Auxilios", q:"¿Cómo se detiene una hemorragia externa?", opts:["Aplicar torniquete siempre","Presión directa sostenida sobre la herida con tela limpia","Lavar la herida con agua fría","Elevar las piernas del herido"], ans:1, exp:"La presión directa y sostenida sobre la herida es la forma más efectiva de controlar una hemorragia externa."},
  {cat:"Primeros Auxilios", q:"¿Qué no se debe dar a una persona accidentada?", opts:["Apoyo emocional","Alimentos o líquidos por vía oral","Abrigo si tiene frío","Mantenerla tranquila"], ans:1, exp:"No se deben dar alimentos ni líquidos a un accidentado: puede necesitar cirugía urgente y podría causar aspiración."},
  // ── MEDIO AMBIENTE Y CONDUCCIÓN
  {cat:"Conducción Segura", q:"¿Qué es el fenómeno de 'aquaplaning'?", opts:["Exceso de velocidad en lluvia","Pérdida de tracción por capa de agua entre neumático y calzada","Fallo del sistema de frenos en mojado","Condensación en el parabrisas"], ans:1, exp:"El aquaplaning ocurre cuando los neumáticos pierden contacto con la calzada al formarse una capa de agua. Solución: soltar el acelerador suavemente."},
  {cat:"Conducción Segura", q:"¿Cómo afecta la lluvia a la distancia de frenado?", opts:["No la afecta","La reduce a la mitad","La aumenta hasta el doble o más","Mejora el frenado"], ans:2, exp:"En piso mojado la distancia de frenado puede duplicarse o triplicarse, por lo que se debe reducir la velocidad."},
  {cat:"Conducción Segura", q:"¿Qué se debe hacer al conducir en neblina densa?", opts:["Encender luces altas para ver mejor","Usar luces bajas y neblineros, reducir velocidad y aumentar distancia","Apagar todas las luces para no deslumbrar","Conducir al centro de la vía"], ans:1, exp:"En neblina se usan luces bajas y neblineros (no altas, rebotan), se reduce la velocidad y se aumenta la distancia de seguimiento."},
  {cat:"Conducción Segura", q:"¿Qué es el punto ciego en un vehículo?", opts:["El retrovisor interior","Zona que no es visible en ningún espejo del vehículo","La parte trasera del vehículo","El área frente al capó"], ans:1, exp:"El punto ciego es la zona lateral-trasera que no aparece en ningún espejo. Siempre verificar girando la cabeza antes de cambiar de carril."},
  {cat:"Conducción Segura", q:"¿Cuál es la posición correcta de las manos en el volante?", opts:["12 y 6 (arriba y abajo)","9 y 3 (lados) o 10 y 2","8 y 4","Una mano al centro"], ans:1, exp:"La posición 9 y 3 (o 10 y 2) ofrece mejor control del volante y permite reaccionar rápido en emergencias."},
  // ── MOTOCICLISTAS
  {cat:"Motociclistas", q:"¿Es obligatorio el uso del casco para el parrillero de una motocicleta?", opts:["Solo en carretera","No, solo el conductor","Sí, siempre para conductor y pasajero","Solo si la moto supera 125cc"], ans:2, exp:"El casco es obligatorio para el conductor y todos los pasajeros de la motocicleta en toda vía pública."},
  {cat:"Motociclistas", q:"¿Cuántas personas pueden viajar en una motocicleta legalmente?", opts:["Solo el conductor","Conductor y un pasajero","Hasta 3 personas si es moto grande","Solo en motos de más de 250cc se permite pasajero"], ans:1, exp:"En una motocicleta solo pueden viajar el conductor y UN pasajero, independientemente de la cilindrada."},
  {cat:"Motociclistas", q:"¿Qué prenda de seguridad adicional se recomienda para motociclistas?", opts:["Solo el casco","Casco, guantes, chaqueta reforzada, botas y pantalón de protección","Chaleco reflectivo solo en la noche","Gafas de sol"], ans:1, exp:"El equipo completo incluye casco certificado, guantes, chaqueta con protecciones, botas y pantalón especializado."},
  {cat:"Motociclistas", q:"¿Pueden las motos transitar por el carril exclusivo de bicicletas (ciclovía)?", opts:["Sí, si van despacio","Sí, cuando el tráfico está congestionado","No, está prohibido","Solo motos eléctricas"], ans:2, exp:"Las ciclovías y ciclocarriles son exclusivos para bicicletas, triciclos y vehículos de movilidad personal no motorizados."},
  // ── PEATONES Y CICLISTAS
  {cat:"Peatones", q:"¿Por dónde deben transitar los peatones en vías sin andén?", opts:["Al centro de la vía","Por la derecha en el sentido del tráfico","Por la izquierda enfrentando el tráfico","Por cualquier lado"], ans:2, exp:"En vías sin andén los peatones deben caminar por la izquierda, mirando de frente el tráfico que viene hacia ellos."},
  {cat:"Peatones", q:"¿En qué lugar tiene prioridad absoluta el peatón?", opts:["En toda la vía pública","Solo en parques","En pasos peatonales demarcados","Solo en zonas escolares"], ans:2, exp:"En los cruces peatonales (cebras) debidamente demarcados, el peatón tiene derecho de vía prioritario."},
  {cat:"Ciclistas", q:"¿Los ciclistas deben respetar los semáforos?", opts:["No, pueden continuar si no hay carros","Sí, las mismas normas que los vehículos motorizados","Solo los semáforos rojos","Solo en vías primarias"], ans:1, exp:"Los ciclistas están sujetos a las mismas normas de tránsito que los vehículos: deben respetar semáforos, señales y prioridades."},
  {cat:"Ciclistas", q:"¿Es obligatorio el uso de chaleco reflectivo para ciclistas en la noche?", opts:["No es obligatorio","Solo en carretera","Sí, siempre al circular de noche en vía pública","Solo en ciclistas menores de edad"], ans:2, exp:"El chaleco o elementos reflectivos son obligatorios para ciclistas al circular en horario nocturno en cualquier vía."},
  // ── INFRACCIONES
  {cat:"Infracciones", q:"¿Qué tipo de infracción es pasar un semáforo en rojo?", opts:["Leve","Grave","Gravísima","No es infracción si no hay peatones"], ans:2, exp:"Pasar un semáforo en rojo es una infracción GRAVÍSIMA que puede generar suspensión de la licencia y multa alta."},
  {cat:"Infracciones", q:"¿Cuál es la sanción por conducir bajo efectos del alcohol en Colombia?", opts:["Solo multa económica","Multa, suspensión de licencia y posiblemente prisión según el nivel","Advertencia verbal","Solo retención del vehículo"], ans:1, exp:"La Ley 1696/2013 establece multas progresivas, suspensión o cancelación de licencia y penas de prisión según el nivel de alcohol."},
  {cat:"Infracciones", q:"¿Se puede usar el celular mientras se conduce?", opts:["Sí, con audífono","Sí, solo para GPS","No, está totalmente prohibido salvo dispositivos manos libres integrados al vehículo","Solo en semáforos en rojo"], ans:2, exp:"El uso del celular al conducir está prohibido. Solo se permite comunicación a través de sistemas integrados de manos libres del vehículo."},
  {cat:"Infracciones", q:"¿Qué es el comparendo?", opts:["El seguro obligatorio del vehículo","El documento que impone una sanción por infracción de tránsito","La licencia de tránsito","El certificado técnico-mecánico"], ans:1, exp:"El comparendo es el documento mediante el cual el agente de tránsito reporta y notifica una infracción al conductor."},
  // ── DOCUMENTOS
  {cat:"Documentos", q:"¿Qué es el SOAT?", opts:["Impuesto vehicular","Seguro Obligatorio de Accidentes de Tránsito que cubre víctimas de accidentes","Certificado técnico-mecánico","Tarjeta de circulación"], ans:1, exp:"El SOAT (Seguro Obligatorio de Accidentes de Tránsito) es obligatorio y cubre gastos médicos y de muerte de víctimas de accidentes."},
  {cat:"Documentos", q:"¿Cada cuánto debe realizarse la revisión técnico-mecánica para vehículos particulares con más de 2 años?", opts:["Cada año","Cada 2 años","Cada 3 años","Solo cuando el vehículo tenga problemas"], ans:1, exp:"Los vehículos particulares con más de 2 años de fabricación deben pasar revisión técnico-mecánica cada 2 años (anual para servicio público)."},
  {cat:"Documentos", q:"¿Qué pasa si conduce sin SOAT vigente?", opts:["Solo advertencia verbal","Inmovilización del vehículo y multa","Solo multa pequeña","No hay sanción"], ans:1, exp:"Circular sin SOAT es infracción grave: el vehículo puede ser inmovilizado hasta que se acredite su adquisición además de la multa."},
  // ── MÁS PREGUNTAS - NORMAS
  {cat:"Normas", q:"¿Qué es la distancia de seguridad lateral?", opts:["La separación con el semáforo","El espacio lateral mínimo al adelantar ciclistas o motocicletas (al menos 1 metro)","La distancia al andén","El ancho del carril"], ans:1, exp:"Al adelantar a ciclistas o motociclistas se debe dejar al menos 1 metro de distancia lateral para su seguridad."},
  {cat:"Normas", q:"¿Está permitido estacionarse en doble fila?", opts:["Sí, si es breve","Sí, con luces de emergencia","No, es una infracción","Solo de noche"], ans:2, exp:"El estacionamiento en doble fila está prohibido pues obstruye la vía. Es infracción sancionable con multa."},
  {cat:"Normas", q:"¿Quién tiene prioridad en una rotonda (glorieta)?", opts:["El vehículo que entra","El vehículo que ya está dentro de la glorieta","El vehículo más grande","Quien lleva más velocidad"], ans:1, exp:"En las glorietas, tienen prioridad los vehículos que ya circulan dentro. Los que entran deben ceder el paso."},
  {cat:"Normas", q:"¿Cuándo está permitido hacer cambio de carril?", opts:["En cualquier momento","Cuando la línea central sea discontinua y haya espacio libre","Solo en autopistas","Nunca, solo en intersecciones"], ans:1, exp:"El cambio de carril es permitido cuando la línea es discontinua, hay visibilidad suficiente, espacio libre y se señaliza con anticipación."},
  {cat:"Normas", q:"¿Qué significa 'zona de no parqueo' marcada en el pavimento?", opts:["Estacionamiento permitido 30 minutos","Prohibición absoluta de estacionar","Solo no parqueo en horas pico","Zona de carga y descarga"], ans:1, exp:"Las zonas demarcadas como 'no parqueo' tienen prohibición absoluta de estacionar en cualquier momento."},
  {cat:"Normas", q:"¿A qué velocidad máxima deben transitar los vehículos en zonas escolares?", opts:["20 km/h","30 km/h","40 km/h","50 km/h"], ans:0, exp:"En zonas escolares la velocidad máxima es 20 km/h para garantizar la seguridad de niños y peatones."},
  {cat:"Normas", q:"¿Es obligatorio detenerse ante un bus escolar que está recogiendo o dejando estudiantes?", opts:["No, si circula en carril contrario","Sí, en ambos sentidos hasta que el bus retome la marcha","Solo si hay estudiantes cruzando","Solo el carril del mismo sentido"], ans:1, exp:"La ley obliga a todos los vehículos a detenerse en ambos sentidos mientras el bus escolar tiene luces intermitentes activas."},
  {cat:"Normas", q:"¿Qué es el 'pico y placa'?", opts:["Restricción de velocidad en horas específicas","Restricción de circulación según el último dígito de la placa en horario y zona determinados","Impuesto de rodamiento","Norma de revisión de frenos"], ans:1, exp:"El pico y placa restringe la circulación de vehículos según el último dígito de su placa en horarios y zonas específicas para reducir la congestión."},
  // ── CONDUCCIÓN SEGURA ADICIONAL
  {cat:"Conducción Segura", q:"¿Qué es la conducción defensiva?", opts:["Conducir lo más rápido posible para llegar pronto","Técnica que permite anticipar riesgos y actuar para evitar accidentes","Conducir solo de día","Usar siempre el carril derecho"], ans:1, exp:"La conducción defensiva busca anticipar y evitar situaciones de riesgo, aún cuando otros cometan errores."},
  {cat:"Conducción Segura", q:"¿Cuántos metros de visibilidad se requieren mínimo para adelantar?", opts:["50 metros","100 metros","200 metros","400 metros"], ans:2, exp:"Para adelantar con seguridad se requiere visibilidad de al menos 200 metros en línea recta y vía libre."},
  {cat:"Conducción Segura", q:"¿Qué debe hacer si siente sueño conduciendo?", opts:["Bajar la ventanilla y continuar","Tomar café y seguir","Detenerse en lugar seguro y descansar","Conducir más rápido para llegar pronto"], ans:2, exp:"El sueño al volante es causa principal de accidentes. Debe detenerse en un lugar seguro y descansar antes de continuar."},
  {cat:"Conducción Segura", q:"¿Qué es el 'efecto túnel' en conducción?", opts:["Conducir por un túnel sin luces","Reducción del campo visual periférico al aumentar la velocidad","Deslumbramiento al salir de un túnel","Pérdida de señal GPS"], ans:1, exp:"A mayor velocidad, el campo visual se estrecha (efecto túnel), reduciendo la capacidad de detectar obstáculos laterales."},
  {cat:"Conducción Segura", q:"¿Cómo afecta el cansancio al tiempo de reacción?", opts:["No lo afecta","Lo mejora (el conductor se concentra más)","Lo aumenta significativamente, retardando la respuesta ante peligros","Solo afecta de noche"], ans:2, exp:"El cansancio aumenta el tiempo de reacción, reduce la concentración y puede causar microsueños al volante."},
  // ── SEÑALES ADICIONALES
  {cat:"Señales", q:"¿Qué indica una señal circular azul con flecha blanca?", opts:["Prohibición de girar","Obligación de seguir la dirección indicada","Recomendación de ruta","Fin de restricción"], ans:1, exp:"Las señales circulares azules con flechas blancas son OBLIGATORIAS: el conductor DEBE seguir la dirección indicada."},
  {cat:"Señales", q:"¿Qué significa una señal rectangular azul con una 'P' blanca?", opts:["Prohibición de parquear","Zona de parqueo permitido","Parqueadero de pago","Parqueadero privado"], ans:1, exp:"La señal azul con P blanca indica zona de parqueo permitido para los vehículos."},
  {cat:"Señales", q:"¿Qué indica una señal de 'zona de derrumbes'?", opts:["Zona de construcción permanente","Zona de riesgo por derrumbes o caída de rocas","Área de minería","Zona de vientos fuertes"], ans:1, exp:"La señal de zona de derrumbes advierte que existe riesgo de caída de material de los taludes. Se debe reducir velocidad y estar alerta."},
  {cat:"Señales", q:"¿Qué señal indica el inicio de una zona urbana?", opts:["Señal rectangular verde con nombre de ciudad","Señal que reduce la velocidad máxima a 60 km/h","Señal rectangular azul","Líneas amarillas en la calzada"], ans:0, exp:"El ingreso a zona urbana se indica con señal rectangular verde con el nombre del municipio o ciudad."},
  // ── VEHÍCULOS Y CARGA
  {cat:"Normas", q:"¿Está prohibido circular en reversa en una autopista o vía de alta velocidad?", opts:["No, si hay emergencia","Sí, absolutamente prohibido","Solo si obstruye el tráfico","Solo de noche"], ans:1, exp:"Circular en reversa en autopistas o vías primarias es una infracción gravísima que pone en peligro la vida."},
  {cat:"Normas", q:"¿Qué se debe hacer si un vehículo se queda varado en la vía?", opts:["Dejarlo en el carril y buscar ayuda","Señalizar con triángulos de emergencia, alejarse del vehículo y llamar a grúa","Empujarlo al arcén rápidamente","Activar solo las luces de emergencia y esperar"], ans:1, exp:"Debe señalizar con triángulos a distancia adecuada, alejarse del vehículo (riesgo de atropello) y llamar a servicio de grúa."},
  {cat:"Normas", q:"¿A qué distancia deben colocarse los triángulos de emergencia?", opts:["5 metros","10 metros","Al menos 50 metros del vehículo","100 metros"], ans:2, exp:"Los triángulos de emergencia deben colocarse al menos a 50 metros del vehículo varado, en cada dirección si la vía es bidireccional."},
  {cat:"Mecánica", q:"¿Para qué sirve el freno de mano o freno de estacionamiento?", opts:["Freno de emergencia principal","Mantener el vehículo detenido en pendientes y estacionamiento","Freno de las ruedas traseras en curvas","Regular la presión del sistema de frenos"], ans:1, exp:"El freno de mano evita que el vehículo se desplace al estar estacionado, especialmente en pendientes."},
  {cat:"Mecánica", q:"¿Qué indica el testigo del ABS en el tablero?", opts:["Sistema de frenos antibloqueo funcionando correctamente","Fallo en el sistema ABS que debe revisarse","El ABS está desactivado intencionalmente","Alerta de pastillas de freno desgastadas"], ans:1, exp:"Si el testigo del ABS permanece encendido mientras se conduce, indica una falla en el sistema que debe revisarse urgentemente."},
  {cat:"Mecánica", q:"¿Qué hace el sistema de frenos ABS?", opts:["Aumenta la potencia de frenado","Impide que las ruedas se bloqueen en frenado brusco permitiendo seguir girando el volante","Activa el freno de emergencia automáticamente","Lubrica el sistema de frenos"], ans:1, exp:"El ABS (Anti-lock Braking System) evita el bloqueo de ruedas en frenado brusco, manteniendo la dirección y reduciendo la distancia de frenado."},
  // ── PREGUNTAS FINALES
  {cat:"Conducción Segura", q:"¿Qué es la 'zona de crumple' de un vehículo moderno?", opts:["El área de las bolsas de aire","Zonas diseñadas para deformarse y absorber energía en un choque protegiendo a los ocupantes","El cinturón de seguridad","El vidrio laminado del parabrisas"], ans:1, exp:"Las zonas de deformación programada absorben la energía del impacto y reducen la fuerza que llega al habitáculo y a los ocupantes."},
  {cat:"Peatones", q:"¿Qué debe hacer un conductor cuando un peatón inicia el cruce en luz verde peatonal?", opts:["Tocar bocina para alertarlo","Continuar si el peatón aún está en el andén","Ceder el paso aunque el semáforo vehicular esté en verde","Reducir velocidad pero continuar"], ans:2, exp:"El peatón que cruce en luz verde peatonal tiene prioridad absoluta. El conductor debe ceder el paso completamente."},
  {cat:"Normas", q:"¿Cuándo está permitido circular por el carril del centro en una vía de tres carriles?", opts:["Siempre, es el carril más rápido","Solo para adelantar, retornando luego al carril derecho","Está prohibido circular por el carril central","Solo camiones y buses"], ans:1, exp:"El carril central de una vía de tres carriles se usa para adelantar y luego se debe retornar al carril derecho."},
  {cat:"Infracciones", q:"¿Qué es la inmovilización de un vehículo?", opts:["Quitar las llantas al vehículo","Retención del vehículo en patio oficial por infracción grave o documentos vencidos","Multa por mal estacionamiento","Suspensión temporal de la licencia"], ans:1, exp:"La inmovilización es la retención del vehículo en instalaciones oficiales hasta que se subsane la infracción (SOAT, revisión técnica, etc.)."},
  {cat:"Conducción Segura", q:"Al conducir en una pendiente pronunciada hacia abajo, ¿qué técnica ayuda a controlar la velocidad sin sobrecalentar los frenos?", opts:["Frenar constantemente","Apagar el motor","Bajar marchas para usar el freno motor","Acelerar controladamente"], ans:2, exp:"En pendientes largas se debe usar el freno motor (bajar marchas) para controlar la velocidad y evitar sobrecalentar los frenos de disco o tambor."},
];
